// @generated by rozectl. DO NOT EDIT.
#![allow(dead_code)]

pub const AUDIT_EVENT_TABLE: &str = "audit_events";
pub const AUDIT_EVENT_FIELDS: &[AuditEventField] = &[
    AuditEventField::Id,
    AuditEventField::UserId,
    AuditEventField::Action,
    AuditEventField::CreatedAt,
];

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum AuditEventField {
    Id,
    UserId,
    Action,
    CreatedAt,
}

impl AuditEventField {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Id => "id",
            Self::UserId => "user_id",
            Self::Action => "action",
            Self::CreatedAt => "created_at",
        }
    }
}
