// @generated by rozectl. DO NOT EDIT.
#![allow(dead_code, unused_imports)]

use super::pet::{PetMutationHooks, PetRepository};
use super::user::{UserMutationHooks, UserRepository};
use crate::svc::ServiceContext;

pub(crate) enum ModelConnection<'a> {
    Database(&'a sea_orm::DatabaseConnection),
    Transaction(&'a sea_orm::DatabaseTransaction),
}

#[async_trait::async_trait]
impl sea_orm::ConnectionTrait for ModelConnection<'_> {
    fn get_database_backend(&self) -> sea_orm::DatabaseBackend {
        match self {
            Self::Database(connection) => connection.get_database_backend(),
            Self::Transaction(transaction) => transaction.get_database_backend(),
        }
    }

    fn support_returning(&self) -> bool {
        match self {
            Self::Database(connection) => connection.support_returning(),
            Self::Transaction(transaction) => transaction.support_returning(),
        }
    }

    fn is_mock_connection(&self) -> bool {
        match self {
            Self::Database(connection) => connection.is_mock_connection(),
            Self::Transaction(transaction) => transaction.is_mock_connection(),
        }
    }

    async fn execute(
        &self,
        statement: sea_orm::Statement,
    ) -> Result<sea_orm::ExecResult, sea_orm::DbErr> {
        match self {
            Self::Database(connection) => connection.execute(statement).await,
            Self::Transaction(transaction) => transaction.execute(statement).await,
        }
    }

    async fn execute_unprepared(&self, sql: &str) -> Result<sea_orm::ExecResult, sea_orm::DbErr> {
        match self {
            Self::Database(connection) => connection.execute_unprepared(sql).await,
            Self::Transaction(transaction) => transaction.execute_unprepared(sql).await,
        }
    }

    async fn query_one(
        &self,
        statement: sea_orm::Statement,
    ) -> Result<Option<sea_orm::QueryResult>, sea_orm::DbErr> {
        match self {
            Self::Database(connection) => connection.query_one(statement).await,
            Self::Transaction(transaction) => transaction.query_one(statement).await,
        }
    }

    async fn query_all(
        &self,
        statement: sea_orm::Statement,
    ) -> Result<Vec<sea_orm::QueryResult>, sea_orm::DbErr> {
        match self {
            Self::Database(connection) => connection.query_all(statement).await,
            Self::Transaction(transaction) => transaction.query_all(statement).await,
        }
    }
}

pub struct TransactionModelClient<'tx> {
    ctx: &'tx ServiceContext,
    transaction: &'tx sea_orm::DatabaseTransaction,
    pending_invalidations: &'tx std::sync::Mutex<Vec<String>>,
    user_mutation_hooks: Vec<&'tx dyn UserMutationHooks>,
    pet_mutation_hooks: Vec<&'tx dyn PetMutationHooks>,
}

impl<'tx> TransactionModelClient<'tx> {
    pub fn user(&self) -> UserRepository<'_> {
        self.user_mutation_hooks.iter().fold(
            UserRepository::new_in_transaction(
                self.ctx,
                self.transaction,
                self.pending_invalidations,
            ),
            |repository, hooks| repository.with_mutation_hooks(*hooks),
        )
    }

    pub fn pet(&self) -> PetRepository<'_> {
        self.pet_mutation_hooks.iter().fold(
            PetRepository::new_in_transaction(
                self.ctx,
                self.transaction,
                self.pending_invalidations,
            ),
            |repository, hooks| repository.with_mutation_hooks(*hooks),
        )
    }
}

pub struct ModelClient<'a> {
    ctx: &'a ServiceContext,
    user_mutation_hooks: Vec<&'a dyn UserMutationHooks>,
    pet_mutation_hooks: Vec<&'a dyn PetMutationHooks>,
}

impl<'a> ModelClient<'a> {
    pub fn new(ctx: &'a ServiceContext) -> Self {
        Self {
            ctx,
            user_mutation_hooks: Vec::new(),
            pet_mutation_hooks: Vec::new(),
        }
    }

    async fn flush_invalidations(
        &self,
        _pending: &std::sync::Mutex<Vec<String>>,
    ) -> anyhow::Result<()> {
        Ok(())
    }

    pub async fn transaction<F, T>(&self, func: F) -> anyhow::Result<T>
    where
        F: for<'tx> FnOnce(
                TransactionModelClient<'tx>,
            ) -> std::pin::Pin<
                Box<dyn std::future::Future<Output = anyhow::Result<T>> + Send + 'tx>,
            > + Send,
        T: Send,
    {
        let database = self.ctx.write_db()?;
        self.transaction_on(database, func).await
    }

    async fn transaction_on<F, T>(
        &self,
        database: &sea_orm::DatabaseConnection,
        func: F,
    ) -> anyhow::Result<T>
    where
        F: for<'tx> FnOnce(
                TransactionModelClient<'tx>,
            ) -> std::pin::Pin<
                Box<dyn std::future::Future<Output = anyhow::Result<T>> + Send + 'tx>,
            > + Send,
        T: Send,
    {
        use sea_orm::TransactionTrait as _;
        tracing::debug!(
            backend = "sea_orm",
            phase = "begin",
            "model transaction phase"
        );
        let transaction = database.begin().await?;
        let pending_invalidations = std::sync::Mutex::new(Vec::new());
        let client = TransactionModelClient {
            ctx: self.ctx,
            transaction: &transaction,
            pending_invalidations: &pending_invalidations,
            user_mutation_hooks: self.user_mutation_hooks.to_vec(),
            pet_mutation_hooks: self.pet_mutation_hooks.to_vec(),
        };
        match func(client).await {
            Ok(value) => {
                transaction.commit().await?;
                tracing::debug!(
                    backend = "sea_orm",
                    phase = "commit",
                    "model transaction phase"
                );
                self.flush_invalidations(&pending_invalidations).await?;
                Ok(value)
            }
            Err(error) => {
                transaction.rollback().await?;
                tracing::debug!(
                    backend = "sea_orm",
                    phase = "rollback",
                    "model transaction phase"
                );
                Err(error)
            }
        }
    }

    pub fn use_user_mutation_hooks(mut self, hooks: &'a dyn UserMutationHooks) -> Self {
        self.user_mutation_hooks.push(hooks);
        self
    }

    pub fn user(&self) -> UserRepository<'a> {
        self.user_mutation_hooks
            .iter()
            .fold(UserRepository::new(self.ctx), |repository, hooks| {
                repository.with_mutation_hooks(*hooks)
            })
    }

    pub fn use_pet_mutation_hooks(mut self, hooks: &'a dyn PetMutationHooks) -> Self {
        self.pet_mutation_hooks.push(hooks);
        self
    }

    pub fn pet(&self) -> PetRepository<'a> {
        self.pet_mutation_hooks
            .iter()
            .fold(PetRepository::new(self.ctx), |repository, hooks| {
                repository.with_mutation_hooks(*hooks)
            })
    }
}
