// @generated by rozectl. DO NOT EDIT.
#![allow(dead_code)]

pub const FRIENDSHIP_TABLE: &str = "friendships";
pub const FRIENDSHIP_FIELDS: &[FriendshipField] = &[
    FriendshipField::Id,
    FriendshipField::UserId,
    FriendshipField::FriendId,
    FriendshipField::CreatedAt,
];

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum FriendshipField {
    Id,
    UserId,
    FriendId,
    CreatedAt,
}

impl FriendshipField {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Id => "id",
            Self::UserId => "user_id",
            Self::FriendId => "friend_id",
            Self::CreatedAt => "created_at",
        }
    }
}
