// @generated by rozectl. DO NOT EDIT.
#![allow(dead_code)]

pub const GROUP_TABLE: &str = "groups";
pub const GROUP_FIELDS: &[GroupField] = &[
    GroupField::Id,
    GroupField::Name,
    GroupField::Description,
    GroupField::CreatedAt,
];

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum GroupField {
    Id,
    Name,
    Description,
    CreatedAt,
}

impl GroupField {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Id => "id",
            Self::Name => "name",
            Self::Description => "description",
            Self::CreatedAt => "created_at",
        }
    }
}
