// @generated by rozectl. DO NOT EDIT.
#![allow(dead_code, unused_imports, deprecated)]

use sea_orm::entity::prelude::*;
use sea_orm::{
    sea_query::{Condition, Expr, ExprTrait, Func, LikeExpr, OnConflict},
    ActiveModelTrait, ColumnTrait, ConnectionTrait, DatabaseBackend, DatabaseConnection,
    DatabaseTransaction, DbErr, DeleteResult, EntityTrait, IntoActiveModel, PaginatorTrait,
    QueryFilter, QueryOrder, QuerySelect, Select, SelectorTrait, Set, TransactionError,
    TransactionTrait, UpdateResult,
};
use serde::{Deserialize, Serialize};
use std::time::Duration;

use super::client::ModelConnection;
use crate::svc::ServiceContext;

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, DeriveEntityModel)]
#[sea_orm(table_name = "locale_settings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub tenant_id: String,
    #[sea_orm(primary_key)]
    pub locale: String,
    pub value: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct LocaleSettingKey {
    pub tenant_id: String,
    pub locale: String,
}

impl Model {
    pub fn fixture(index: u64) -> Self {
        Self {
            tenant_id: format!("fixture-locale_setting-tenant_id-{index}"),
            locale: format!("fixture-locale_setting-locale-{index}"),
            value: format!("fixture-locale_setting-value-{index}"),
        }
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum LocaleSettingOrder {
    TenantIdAsc,
    TenantIdDesc,
    LocaleAsc,
    LocaleDesc,
    ValueAsc,
    ValueDesc,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum LocaleSettingPredicate {
    TenantIdEq(String),
    TenantIdNe(String),
    TenantIdIn(Vec<String>),
    TenantIdNotIn(Vec<String>),
    TenantIdContains(String),
    TenantIdNotContains(String),
    TenantIdIContains(String),
    TenantIdNotIContains(String),
    TenantIdEqualFold(String),
    TenantIdNotEqualFold(String),
    TenantIdStartsWith(String),
    TenantIdNotStartsWith(String),
    TenantIdEndsWith(String),
    TenantIdNotEndsWith(String),
    LocaleEq(String),
    LocaleNe(String),
    LocaleIn(Vec<String>),
    LocaleNotIn(Vec<String>),
    LocaleContains(String),
    LocaleNotContains(String),
    LocaleIContains(String),
    LocaleNotIContains(String),
    LocaleEqualFold(String),
    LocaleNotEqualFold(String),
    LocaleStartsWith(String),
    LocaleNotStartsWith(String),
    LocaleEndsWith(String),
    LocaleNotEndsWith(String),
    ValueEq(String),
    ValueNe(String),
    ValueIn(Vec<String>),
    ValueNotIn(Vec<String>),
    ValueContains(String),
    ValueNotContains(String),
    ValueIContains(String),
    ValueNotIContains(String),
    ValueEqualFold(String),
    ValueNotEqualFold(String),
    ValueStartsWith(String),
    ValueNotStartsWith(String),
    ValueEndsWith(String),
    ValueNotEndsWith(String),
    And(Vec<LocaleSettingPredicate>),
    Or(Vec<LocaleSettingPredicate>),
    Not(Box<LocaleSettingPredicate>),
}

pub fn tenant_id_eq(value: String) -> LocaleSettingPredicate {
    LocaleSettingPredicate::TenantIdEq(value)
}
pub fn tenant_id_ne(value: String) -> LocaleSettingPredicate {
    LocaleSettingPredicate::TenantIdNe(value)
}
pub fn tenant_id_in(values: Vec<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::TenantIdIn(values)
}
pub fn tenant_id_not_in(values: Vec<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::TenantIdNotIn(values)
}
pub fn tenant_id_contains(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::TenantIdContains(value.into())
}
pub fn tenant_id_not_contains(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::TenantIdNotContains(value.into())
}
pub fn tenant_id_icontains(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::TenantIdIContains(value.into())
}
pub fn tenant_id_not_icontains(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::TenantIdNotIContains(value.into())
}
pub fn tenant_id_equal_fold(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::TenantIdEqualFold(value.into())
}
pub fn tenant_id_not_equal_fold(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::TenantIdNotEqualFold(value.into())
}
pub fn tenant_id_starts_with(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::TenantIdStartsWith(value.into())
}
pub fn tenant_id_not_starts_with(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::TenantIdNotStartsWith(value.into())
}
pub fn tenant_id_ends_with(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::TenantIdEndsWith(value.into())
}
pub fn tenant_id_not_ends_with(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::TenantIdNotEndsWith(value.into())
}
pub fn locale_eq(value: String) -> LocaleSettingPredicate {
    LocaleSettingPredicate::LocaleEq(value)
}
pub fn locale_ne(value: String) -> LocaleSettingPredicate {
    LocaleSettingPredicate::LocaleNe(value)
}
pub fn locale_in(values: Vec<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::LocaleIn(values)
}
pub fn locale_not_in(values: Vec<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::LocaleNotIn(values)
}
pub fn locale_contains(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::LocaleContains(value.into())
}
pub fn locale_not_contains(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::LocaleNotContains(value.into())
}
pub fn locale_icontains(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::LocaleIContains(value.into())
}
pub fn locale_not_icontains(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::LocaleNotIContains(value.into())
}
pub fn locale_equal_fold(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::LocaleEqualFold(value.into())
}
pub fn locale_not_equal_fold(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::LocaleNotEqualFold(value.into())
}
pub fn locale_starts_with(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::LocaleStartsWith(value.into())
}
pub fn locale_not_starts_with(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::LocaleNotStartsWith(value.into())
}
pub fn locale_ends_with(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::LocaleEndsWith(value.into())
}
pub fn locale_not_ends_with(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::LocaleNotEndsWith(value.into())
}
pub fn value_eq(value: String) -> LocaleSettingPredicate {
    LocaleSettingPredicate::ValueEq(value)
}
pub fn value_ne(value: String) -> LocaleSettingPredicate {
    LocaleSettingPredicate::ValueNe(value)
}
pub fn value_in(values: Vec<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::ValueIn(values)
}
pub fn value_not_in(values: Vec<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::ValueNotIn(values)
}
pub fn value_contains(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::ValueContains(value.into())
}
pub fn value_not_contains(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::ValueNotContains(value.into())
}
pub fn value_icontains(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::ValueIContains(value.into())
}
pub fn value_not_icontains(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::ValueNotIContains(value.into())
}
pub fn value_equal_fold(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::ValueEqualFold(value.into())
}
pub fn value_not_equal_fold(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::ValueNotEqualFold(value.into())
}
pub fn value_starts_with(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::ValueStartsWith(value.into())
}
pub fn value_not_starts_with(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::ValueNotStartsWith(value.into())
}
pub fn value_ends_with(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::ValueEndsWith(value.into())
}
pub fn value_not_ends_with(value: impl Into<String>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::ValueNotEndsWith(value.into())
}
pub fn and(predicates: Vec<LocaleSettingPredicate>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::And(predicates)
}
pub fn or(predicates: Vec<LocaleSettingPredicate>) -> LocaleSettingPredicate {
    LocaleSettingPredicate::Or(predicates)
}
pub fn not(predicate: LocaleSettingPredicate) -> LocaleSettingPredicate {
    LocaleSettingPredicate::Not(Box::new(predicate))
}
pub fn tenant_id_asc() -> LocaleSettingOrder {
    LocaleSettingOrder::TenantIdAsc
}
pub fn tenant_id_desc() -> LocaleSettingOrder {
    LocaleSettingOrder::TenantIdDesc
}
pub fn locale_asc() -> LocaleSettingOrder {
    LocaleSettingOrder::LocaleAsc
}
pub fn locale_desc() -> LocaleSettingOrder {
    LocaleSettingOrder::LocaleDesc
}
pub fn value_asc() -> LocaleSettingOrder {
    LocaleSettingOrder::ValueAsc
}
pub fn value_desc() -> LocaleSettingOrder {
    LocaleSettingOrder::ValueDesc
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct LocaleSettingPage {
    pub items: Vec<Model>,
    pub total: u64,
    pub page: u64,
    pub page_size: u64,
}

pub trait LocaleSettingLoadedNode {
    fn loaded_node(&self) -> &Model;
}
impl LocaleSettingLoadedNode for Model {
    fn loaded_node(&self) -> &Model {
        self
    }
}

pub struct LocaleSettingQuery<'repo, 'ctx> {
    repo: &'repo LocaleSettingRepository<'ctx>,
    interceptors: Vec<
        std::sync::Arc<dyn roze_orm::OperationMiddleware<Self, Vec<Model>, anyhow::Error> + 'repo>,
    >,
    atomic_interceptors:
        Vec<std::sync::Arc<dyn roze_orm::OperationMiddleware<Self, u64, anyhow::Error> + 'repo>>,
    predicates: Vec<LocaleSettingPredicate>,
    orders: Vec<LocaleSettingOrder>,
    limit: Option<u64>,
    offset: Option<u64>,
    page: Option<(u64, u64)>,
    read_source: roze_orm::ReadSource,
}

impl<'repo, 'ctx> LocaleSettingQuery<'repo, 'ctx> {
    pub fn intercept<F>(self, interceptor: F) -> Self
    where
        F: FnOnce(Self) -> Self,
    {
        interceptor(self)
    }

    pub fn around<I>(mut self, interceptor: I) -> Self
    where
        I: roze_orm::OperationMiddleware<Self, Vec<Model>, anyhow::Error> + 'repo,
    {
        self.interceptors.push(std::sync::Arc::new(interceptor));
        self
    }

    pub fn atomic_around<I>(mut self, interceptor: I) -> Self
    where
        I: roze_orm::OperationMiddleware<Self, u64, anyhow::Error> + 'repo,
    {
        self.atomic_interceptors
            .push(std::sync::Arc::new(interceptor));
        self
    }

    pub fn policy<I, D>(mut self, rules: I, deny_by_default: D) -> Self
    where
        I: IntoIterator<
            Item = std::sync::Arc<dyn roze_orm::Policy<Self, Error = anyhow::Error> + 'repo>,
        >,
        D: Fn() -> anyhow::Error + Send + Sync + 'repo,
    {
        let policy = roze_orm::PolicyMiddleware::new(rules, deny_by_default);
        self.interceptors.push(std::sync::Arc::new(policy.clone()));
        self.atomic_interceptors.push(std::sync::Arc::new(policy));
        self
    }

    pub fn mixin<M>(self, mixin: M) -> Self
    where
        M: roze_orm::OperationMixin<Self>,
    {
        mixin.apply(self)
    }

    pub fn new(repo: &'repo LocaleSettingRepository<'ctx>) -> Self {
        Self {
            repo,
            interceptors: Vec::new(),
            atomic_interceptors: Vec::new(),
            predicates: Vec::new(),
            orders: Vec::new(),
            limit: None,
            offset: None,
            page: None,
            read_source: roze_orm::ReadSource::Replica,
        }
    }

    pub fn read_from(mut self, source: roze_orm::ReadSource) -> Self {
        self.read_source = source;
        self
    }

    pub fn primary(self) -> Self {
        self.read_from(roze_orm::ReadSource::Primary)
    }

    fn read_db(&self) -> anyhow::Result<ModelConnection<'_>> {
        self.repo.read_db_from(self.read_source)
    }

    pub fn where_(mut self, predicate: LocaleSettingPredicate) -> Self {
        self.predicates.push(predicate);
        self
    }

    pub fn where_all<I>(mut self, predicates: I) -> Self
    where
        I: IntoIterator<Item = LocaleSettingPredicate>,
    {
        self.predicates.extend(predicates);
        self
    }

    pub fn where_any<I>(mut self, predicates: I) -> Self
    where
        I: IntoIterator<Item = LocaleSettingPredicate>,
    {
        let predicates = predicates.into_iter().collect::<Vec<_>>();
        if !predicates.is_empty() {
            self.predicates.push(LocaleSettingPredicate::Or(predicates));
        }
        self
    }

    pub fn where_not(mut self, predicate: LocaleSettingPredicate) -> Self {
        self.predicates
            .push(LocaleSettingPredicate::Not(Box::new(predicate)));
        self
    }

    pub fn where_none<I>(mut self, predicates: I) -> Self
    where
        I: IntoIterator<Item = LocaleSettingPredicate>,
    {
        let predicates = predicates.into_iter().collect::<Vec<_>>();
        if !predicates.is_empty() {
            self.predicates.push(LocaleSettingPredicate::Not(Box::new(
                LocaleSettingPredicate::Or(predicates),
            )));
        }
        self
    }

    pub fn order(mut self, order: LocaleSettingOrder) -> Self {
        self.orders.push(order);
        self
    }

    pub fn order_all<I>(mut self, orders: I) -> Self
    where
        I: IntoIterator<Item = LocaleSettingOrder>,
    {
        self.orders.extend(orders);
        self
    }

    pub fn order_by_tenant_id_asc(mut self) -> Self {
        self.orders.push(LocaleSettingOrder::TenantIdAsc);
        self
    }

    pub fn order_by_tenant_id_desc(mut self) -> Self {
        self.orders.push(LocaleSettingOrder::TenantIdDesc);
        self
    }

    pub fn order_by_locale_asc(mut self) -> Self {
        self.orders.push(LocaleSettingOrder::LocaleAsc);
        self
    }

    pub fn order_by_locale_desc(mut self) -> Self {
        self.orders.push(LocaleSettingOrder::LocaleDesc);
        self
    }

    pub fn order_by_value_asc(mut self) -> Self {
        self.orders.push(LocaleSettingOrder::ValueAsc);
        self
    }

    pub fn order_by_value_desc(mut self) -> Self {
        self.orders.push(LocaleSettingOrder::ValueDesc);
        self
    }

    pub fn limit(mut self, limit: u64) -> Self {
        self.limit = Some(limit);
        self
    }

    pub fn offset(mut self, offset: u64) -> Self {
        self.offset = Some(offset);
        self
    }

    pub fn paginate(mut self, page: u64, page_size: u64) -> Self {
        self.page = Some((page, page_size));
        self
    }

    fn predicate_condition(predicate: &LocaleSettingPredicate) -> Condition {
        match predicate {
            LocaleSettingPredicate::TenantIdEq(value) => {
                Condition::all().add(Column::TenantId.eq(value.clone()))
            }
            LocaleSettingPredicate::TenantIdNe(value) => {
                Condition::all().add(Column::TenantId.ne(value.clone()))
            }
            LocaleSettingPredicate::TenantIdIn(values) => {
                Condition::all().add(Column::TenantId.is_in(values.clone()))
            }
            LocaleSettingPredicate::TenantIdNotIn(values) => {
                Condition::all().add(Column::TenantId.is_not_in(values.clone()))
            }
            LocaleSettingPredicate::TenantIdContains(value) => Condition::all().add(
                Column::TenantId.like(LikeExpr::new(contains_like_pattern(value)).escape('\\')),
            ),
            LocaleSettingPredicate::TenantIdNotContains(value) => Condition::all()
                .add(
                    Column::TenantId.like(LikeExpr::new(contains_like_pattern(value)).escape('\\')),
                )
                .not(),
            LocaleSettingPredicate::TenantIdIContains(value) => Condition::all()
                .add(Func::lower(Expr::col(Column::TenantId)).like(
                    LikeExpr::new(contains_like_pattern(&value.to_lowercase())).escape('\\'),
                )),
            LocaleSettingPredicate::TenantIdNotIContains(value) => {
                Condition::all()
                    .add(Func::lower(Expr::col(Column::TenantId)).like(
                        LikeExpr::new(contains_like_pattern(&value.to_lowercase())).escape('\\'),
                    ))
                    .not()
            }
            LocaleSettingPredicate::TenantIdEqualFold(value) => Condition::all().add(
                Func::lower(Expr::col(Column::TenantId))
                    .like(LikeExpr::new(escape_like_pattern(&value.to_lowercase())).escape('\\')),
            ),
            LocaleSettingPredicate::TenantIdNotEqualFold(value) => {
                Condition::all()
                    .add(Func::lower(Expr::col(Column::TenantId)).like(
                        LikeExpr::new(escape_like_pattern(&value.to_lowercase())).escape('\\'),
                    ))
                    .not()
            }
            LocaleSettingPredicate::TenantIdStartsWith(value) => Condition::all().add(
                Column::TenantId
                    .like(LikeExpr::new(format!("{}%", escape_like_pattern(value))).escape('\\')),
            ),
            LocaleSettingPredicate::TenantIdNotStartsWith(value) => {
                Condition::all()
                    .add(Column::TenantId.like(
                        LikeExpr::new(format!("{}%", escape_like_pattern(value))).escape('\\'),
                    ))
                    .not()
            }
            LocaleSettingPredicate::TenantIdEndsWith(value) => Condition::all().add(
                Column::TenantId
                    .like(LikeExpr::new(format!("%{}", escape_like_pattern(value))).escape('\\')),
            ),
            LocaleSettingPredicate::TenantIdNotEndsWith(value) => {
                Condition::all()
                    .add(Column::TenantId.like(
                        LikeExpr::new(format!("%{}", escape_like_pattern(value))).escape('\\'),
                    ))
                    .not()
            }
            LocaleSettingPredicate::LocaleEq(value) => {
                Condition::all().add(Column::Locale.eq(value.clone()))
            }
            LocaleSettingPredicate::LocaleNe(value) => {
                Condition::all().add(Column::Locale.ne(value.clone()))
            }
            LocaleSettingPredicate::LocaleIn(values) => {
                Condition::all().add(Column::Locale.is_in(values.clone()))
            }
            LocaleSettingPredicate::LocaleNotIn(values) => {
                Condition::all().add(Column::Locale.is_not_in(values.clone()))
            }
            LocaleSettingPredicate::LocaleContains(value) => Condition::all()
                .add(Column::Locale.like(LikeExpr::new(contains_like_pattern(value)).escape('\\'))),
            LocaleSettingPredicate::LocaleNotContains(value) => Condition::all()
                .add(Column::Locale.like(LikeExpr::new(contains_like_pattern(value)).escape('\\')))
                .not(),
            LocaleSettingPredicate::LocaleIContains(value) => Condition::all()
                .add(Func::lower(Expr::col(Column::Locale)).like(
                    LikeExpr::new(contains_like_pattern(&value.to_lowercase())).escape('\\'),
                )),
            LocaleSettingPredicate::LocaleNotIContains(value) => {
                Condition::all()
                    .add(Func::lower(Expr::col(Column::Locale)).like(
                        LikeExpr::new(contains_like_pattern(&value.to_lowercase())).escape('\\'),
                    ))
                    .not()
            }
            LocaleSettingPredicate::LocaleEqualFold(value) => Condition::all().add(
                Func::lower(Expr::col(Column::Locale))
                    .like(LikeExpr::new(escape_like_pattern(&value.to_lowercase())).escape('\\')),
            ),
            LocaleSettingPredicate::LocaleNotEqualFold(value) => {
                Condition::all()
                    .add(Func::lower(Expr::col(Column::Locale)).like(
                        LikeExpr::new(escape_like_pattern(&value.to_lowercase())).escape('\\'),
                    ))
                    .not()
            }
            LocaleSettingPredicate::LocaleStartsWith(value) => Condition::all().add(
                Column::Locale
                    .like(LikeExpr::new(format!("{}%", escape_like_pattern(value))).escape('\\')),
            ),
            LocaleSettingPredicate::LocaleNotStartsWith(value) => {
                Condition::all()
                    .add(Column::Locale.like(
                        LikeExpr::new(format!("{}%", escape_like_pattern(value))).escape('\\'),
                    ))
                    .not()
            }
            LocaleSettingPredicate::LocaleEndsWith(value) => Condition::all().add(
                Column::Locale
                    .like(LikeExpr::new(format!("%{}", escape_like_pattern(value))).escape('\\')),
            ),
            LocaleSettingPredicate::LocaleNotEndsWith(value) => {
                Condition::all()
                    .add(Column::Locale.like(
                        LikeExpr::new(format!("%{}", escape_like_pattern(value))).escape('\\'),
                    ))
                    .not()
            }
            LocaleSettingPredicate::ValueEq(value) => {
                Condition::all().add(Column::Value.eq(value.clone()))
            }
            LocaleSettingPredicate::ValueNe(value) => {
                Condition::all().add(Column::Value.ne(value.clone()))
            }
            LocaleSettingPredicate::ValueIn(values) => {
                Condition::all().add(Column::Value.is_in(values.clone()))
            }
            LocaleSettingPredicate::ValueNotIn(values) => {
                Condition::all().add(Column::Value.is_not_in(values.clone()))
            }
            LocaleSettingPredicate::ValueContains(value) => Condition::all()
                .add(Column::Value.like(LikeExpr::new(contains_like_pattern(value)).escape('\\'))),
            LocaleSettingPredicate::ValueNotContains(value) => Condition::all()
                .add(Column::Value.like(LikeExpr::new(contains_like_pattern(value)).escape('\\')))
                .not(),
            LocaleSettingPredicate::ValueIContains(value) => Condition::all()
                .add(Func::lower(Expr::col(Column::Value)).like(
                    LikeExpr::new(contains_like_pattern(&value.to_lowercase())).escape('\\'),
                )),
            LocaleSettingPredicate::ValueNotIContains(value) => {
                Condition::all()
                    .add(Func::lower(Expr::col(Column::Value)).like(
                        LikeExpr::new(contains_like_pattern(&value.to_lowercase())).escape('\\'),
                    ))
                    .not()
            }
            LocaleSettingPredicate::ValueEqualFold(value) => Condition::all().add(
                Func::lower(Expr::col(Column::Value))
                    .like(LikeExpr::new(escape_like_pattern(&value.to_lowercase())).escape('\\')),
            ),
            LocaleSettingPredicate::ValueNotEqualFold(value) => {
                Condition::all()
                    .add(Func::lower(Expr::col(Column::Value)).like(
                        LikeExpr::new(escape_like_pattern(&value.to_lowercase())).escape('\\'),
                    ))
                    .not()
            }
            LocaleSettingPredicate::ValueStartsWith(value) => Condition::all().add(
                Column::Value
                    .like(LikeExpr::new(format!("{}%", escape_like_pattern(value))).escape('\\')),
            ),
            LocaleSettingPredicate::ValueNotStartsWith(value) => {
                Condition::all()
                    .add(Column::Value.like(
                        LikeExpr::new(format!("{}%", escape_like_pattern(value))).escape('\\'),
                    ))
                    .not()
            }
            LocaleSettingPredicate::ValueEndsWith(value) => Condition::all().add(
                Column::Value
                    .like(LikeExpr::new(format!("%{}", escape_like_pattern(value))).escape('\\')),
            ),
            LocaleSettingPredicate::ValueNotEndsWith(value) => {
                Condition::all()
                    .add(Column::Value.like(
                        LikeExpr::new(format!("%{}", escape_like_pattern(value))).escape('\\'),
                    ))
                    .not()
            }
            LocaleSettingPredicate::And(predicates) => predicates
                .iter()
                .fold(Condition::all(), |condition, predicate| {
                    condition.add(Self::predicate_condition(predicate))
                }),
            LocaleSettingPredicate::Or(predicates) => predicates
                .iter()
                .fold(Condition::any(), |condition, predicate| {
                    condition.add(Self::predicate_condition(predicate))
                }),
            LocaleSettingPredicate::Not(predicate) => Condition::all()
                .add(Self::predicate_condition(predicate))
                .not(),
        }
    }

    fn build_filter_select(&self) -> Select<Entity> {
        let mut select = Entity::find();
        for predicate in &self.predicates {
            select = select.filter(Self::predicate_condition(predicate));
        }
        select
    }

    fn apply_order(&self, mut select: Select<Entity>) -> Select<Entity> {
        for order in &self.orders {
            match order {
                LocaleSettingOrder::TenantIdAsc => select = select.order_by_asc(Column::TenantId),
                LocaleSettingOrder::TenantIdDesc => select = select.order_by_desc(Column::TenantId),
                LocaleSettingOrder::LocaleAsc => select = select.order_by_asc(Column::Locale),
                LocaleSettingOrder::LocaleDesc => select = select.order_by_desc(Column::Locale),
                LocaleSettingOrder::ValueAsc => select = select.order_by_asc(Column::Value),
                LocaleSettingOrder::ValueDesc => select = select.order_by_desc(Column::Value),
            }
        }
        select
    }

    fn build_select(&self) -> Select<Entity> {
        let mut select = self.apply_order(self.build_filter_select());
        if let Some(limit) = self.limit {
            select = select.limit(limit);
        }
        if let Some(offset) = self.offset {
            select = select.offset(offset);
        }
        select
    }

    /// Converts this typed query into the backend-native SeaORM select.
    /// Predicates, soft-delete scope, ordering and pagination are preserved.
    pub fn into_select(self) -> Select<Entity> {
        self.build_select()
    }

    pub async fn count(self) -> anyhow::Result<u64> {
        let db = self.repo.read_db_from(self.read_source)?;
        Ok(self.build_filter_select().count(&db).await?)
    }

    pub async fn exists(self) -> anyhow::Result<bool> {
        Ok(self.count().await? > 0)
    }

    pub async fn all(mut self) -> anyhow::Result<Vec<Model>> {
        let interceptors = std::mem::take(&mut self.interceptors);
        roze_orm::execute_chain(&LocaleSettingQueryTerminal, &interceptors, self).await
    }

    async fn all_unintercepted(self) -> anyhow::Result<Vec<Model>> {
        tracing::debug!(model = "LocaleSetting", backend = "sea_orm", source = self.read_source.label(), query_type = "all", predicate_count = self.predicates.len(), order_count = self.orders.len(), limit = ?self.limit, offset = ?self.offset, "model query executing");
        let db = self.repo.read_db_from(self.read_source)?;
        Ok(self.build_select().all(&db).await?)
    }

    pub async fn ids(self) -> anyhow::Result<Vec<String>> {
        let db = self.repo.read_db_from(self.read_source)?;
        Ok(self
            .build_select()
            .select_only()
            .column(Column::TenantId)
            .into_tuple::<String>()
            .all(&db)
            .await?)
    }

    pub async fn first_id(mut self) -> anyhow::Result<Option<String>> {
        self.limit = Some(1);
        Ok(self.ids().await?.into_iter().next())
    }

    pub async fn only_id(mut self) -> anyhow::Result<String> {
        self.limit = Some(2);
        let mut ids = self.ids().await?;
        match ids.len() {
            1 => Ok(ids.remove(0)),
            0 => anyhow::bail!("expected exactly one LocaleSetting id, found none"),
            _ => anyhow::bail!("expected exactly one LocaleSetting id, found multiple"),
        }
    }

    pub async fn pluck_tenant_id(self) -> anyhow::Result<Vec<String>> {
        let db = self.repo.read_db_from(self.read_source)?;
        Ok(self
            .build_select()
            .select_only()
            .column(Column::TenantId)
            .into_tuple::<String>()
            .all(&db)
            .await?)
    }

    pub async fn count_by_tenant_id(self) -> anyhow::Result<Vec<(String, u64)>> {
        let db = self.repo.read_db_from(self.read_source)?;
        let rows = self
            .build_filter_select()
            .select_only()
            .column(Column::TenantId)
            .column_as(Column::TenantId.count(), "roze_count")
            .group_by(Column::TenantId)
            .into_tuple::<(String, i64)>()
            .all(&db)
            .await?;
        Ok(rows
            .into_iter()
            .map(|(value, count)| (value, count as u64))
            .collect())
    }

    pub async fn count_by_tenant_id_having_at_least(
        self,
        minimum: u64,
    ) -> anyhow::Result<Vec<(String, u64)>> {
        let db = self.repo.read_db_from(self.read_source)?;
        let rows = self
            .build_filter_select()
            .select_only()
            .column(Column::TenantId)
            .column_as(Column::TenantId.count(), "roze_count")
            .group_by(Column::TenantId)
            .having(Column::TenantId.count().gte(minimum as i64))
            .into_tuple::<(String, i64)>()
            .all(&db)
            .await?;
        Ok(rows
            .into_iter()
            .map(|(value, count)| (value, count as u64))
            .collect())
    }

    pub async fn count_by_tenant_id_having_at_most(
        self,
        maximum: u64,
    ) -> anyhow::Result<Vec<(String, u64)>> {
        let db = self.repo.read_db_from(self.read_source)?;
        let rows = self
            .build_filter_select()
            .select_only()
            .column(Column::TenantId)
            .column_as(Column::TenantId.count(), "roze_count")
            .group_by(Column::TenantId)
            .having(Column::TenantId.count().lte(maximum as i64))
            .into_tuple::<(String, i64)>()
            .all(&db)
            .await?;
        Ok(rows
            .into_iter()
            .map(|(value, count)| (value, count as u64))
            .collect())
    }

    pub async fn count_by_tenant_id_having_between(
        self,
        minimum: u64,
        maximum: u64,
    ) -> anyhow::Result<Vec<(String, u64)>> {
        let db = self.repo.read_db_from(self.read_source)?;
        let count = Column::TenantId.count();
        let rows = self
            .build_filter_select()
            .select_only()
            .column(Column::TenantId)
            .column_as(count.clone(), "roze_count")
            .group_by(Column::TenantId)
            .having(count.clone().gte(minimum as i64))
            .having(count.lte(maximum as i64))
            .into_tuple::<(String, i64)>()
            .all(&db)
            .await?;
        Ok(rows
            .into_iter()
            .map(|(value, count)| (value, count as u64))
            .collect())
    }

    pub async fn unique_tenant_id(self) -> anyhow::Result<Vec<String>> {
        let values = self
            .pluck_tenant_id()
            .await?
            .into_iter()
            .collect::<std::collections::BTreeSet<_>>();
        Ok(values.into_iter().collect())
    }

    pub async fn pluck_locale(self) -> anyhow::Result<Vec<String>> {
        let db = self.repo.read_db_from(self.read_source)?;
        Ok(self
            .build_select()
            .select_only()
            .column(Column::Locale)
            .into_tuple::<String>()
            .all(&db)
            .await?)
    }

    pub async fn count_by_locale(self) -> anyhow::Result<Vec<(String, u64)>> {
        let db = self.repo.read_db_from(self.read_source)?;
        let rows = self
            .build_filter_select()
            .select_only()
            .column(Column::Locale)
            .column_as(Column::Locale.count(), "roze_count")
            .group_by(Column::Locale)
            .into_tuple::<(String, i64)>()
            .all(&db)
            .await?;
        Ok(rows
            .into_iter()
            .map(|(value, count)| (value, count as u64))
            .collect())
    }

    pub async fn count_by_locale_having_at_least(
        self,
        minimum: u64,
    ) -> anyhow::Result<Vec<(String, u64)>> {
        let db = self.repo.read_db_from(self.read_source)?;
        let rows = self
            .build_filter_select()
            .select_only()
            .column(Column::Locale)
            .column_as(Column::Locale.count(), "roze_count")
            .group_by(Column::Locale)
            .having(Column::Locale.count().gte(minimum as i64))
            .into_tuple::<(String, i64)>()
            .all(&db)
            .await?;
        Ok(rows
            .into_iter()
            .map(|(value, count)| (value, count as u64))
            .collect())
    }

    pub async fn count_by_locale_having_at_most(
        self,
        maximum: u64,
    ) -> anyhow::Result<Vec<(String, u64)>> {
        let db = self.repo.read_db_from(self.read_source)?;
        let rows = self
            .build_filter_select()
            .select_only()
            .column(Column::Locale)
            .column_as(Column::Locale.count(), "roze_count")
            .group_by(Column::Locale)
            .having(Column::Locale.count().lte(maximum as i64))
            .into_tuple::<(String, i64)>()
            .all(&db)
            .await?;
        Ok(rows
            .into_iter()
            .map(|(value, count)| (value, count as u64))
            .collect())
    }

    pub async fn count_by_locale_having_between(
        self,
        minimum: u64,
        maximum: u64,
    ) -> anyhow::Result<Vec<(String, u64)>> {
        let db = self.repo.read_db_from(self.read_source)?;
        let count = Column::Locale.count();
        let rows = self
            .build_filter_select()
            .select_only()
            .column(Column::Locale)
            .column_as(count.clone(), "roze_count")
            .group_by(Column::Locale)
            .having(count.clone().gte(minimum as i64))
            .having(count.lte(maximum as i64))
            .into_tuple::<(String, i64)>()
            .all(&db)
            .await?;
        Ok(rows
            .into_iter()
            .map(|(value, count)| (value, count as u64))
            .collect())
    }

    pub async fn unique_locale(self) -> anyhow::Result<Vec<String>> {
        let values = self
            .pluck_locale()
            .await?
            .into_iter()
            .collect::<std::collections::BTreeSet<_>>();
        Ok(values.into_iter().collect())
    }

    pub async fn first_locale(mut self) -> anyhow::Result<Option<String>> {
        self.limit = Some(1);
        Ok(self.pluck_locale().await?.into_iter().next())
    }

    pub async fn only_locale(mut self) -> anyhow::Result<String> {
        self.limit = Some(2);
        let mut values = self.pluck_locale().await?;
        match values.len() {
            1 => Ok(values.remove(0)),
            0 => anyhow::bail!("expected exactly one LocaleSetting.locale value, found none"),
            _ => anyhow::bail!("expected exactly one LocaleSetting.locale value, found multiple"),
        }
    }

    pub async fn pluck_value(self) -> anyhow::Result<Vec<String>> {
        let db = self.repo.read_db_from(self.read_source)?;
        Ok(self
            .build_select()
            .select_only()
            .column(Column::Value)
            .into_tuple::<String>()
            .all(&db)
            .await?)
    }

    pub async fn count_by_value(self) -> anyhow::Result<Vec<(String, u64)>> {
        let db = self.repo.read_db_from(self.read_source)?;
        let rows = self
            .build_filter_select()
            .select_only()
            .column(Column::Value)
            .column_as(Column::Value.count(), "roze_count")
            .group_by(Column::Value)
            .into_tuple::<(String, i64)>()
            .all(&db)
            .await?;
        Ok(rows
            .into_iter()
            .map(|(value, count)| (value, count as u64))
            .collect())
    }

    pub async fn count_by_value_having_at_least(
        self,
        minimum: u64,
    ) -> anyhow::Result<Vec<(String, u64)>> {
        let db = self.repo.read_db_from(self.read_source)?;
        let rows = self
            .build_filter_select()
            .select_only()
            .column(Column::Value)
            .column_as(Column::Value.count(), "roze_count")
            .group_by(Column::Value)
            .having(Column::Value.count().gte(minimum as i64))
            .into_tuple::<(String, i64)>()
            .all(&db)
            .await?;
        Ok(rows
            .into_iter()
            .map(|(value, count)| (value, count as u64))
            .collect())
    }

    pub async fn count_by_value_having_at_most(
        self,
        maximum: u64,
    ) -> anyhow::Result<Vec<(String, u64)>> {
        let db = self.repo.read_db_from(self.read_source)?;
        let rows = self
            .build_filter_select()
            .select_only()
            .column(Column::Value)
            .column_as(Column::Value.count(), "roze_count")
            .group_by(Column::Value)
            .having(Column::Value.count().lte(maximum as i64))
            .into_tuple::<(String, i64)>()
            .all(&db)
            .await?;
        Ok(rows
            .into_iter()
            .map(|(value, count)| (value, count as u64))
            .collect())
    }

    pub async fn count_by_value_having_between(
        self,
        minimum: u64,
        maximum: u64,
    ) -> anyhow::Result<Vec<(String, u64)>> {
        let db = self.repo.read_db_from(self.read_source)?;
        let count = Column::Value.count();
        let rows = self
            .build_filter_select()
            .select_only()
            .column(Column::Value)
            .column_as(count.clone(), "roze_count")
            .group_by(Column::Value)
            .having(count.clone().gte(minimum as i64))
            .having(count.lte(maximum as i64))
            .into_tuple::<(String, i64)>()
            .all(&db)
            .await?;
        Ok(rows
            .into_iter()
            .map(|(value, count)| (value, count as u64))
            .collect())
    }

    pub async fn unique_value(self) -> anyhow::Result<Vec<String>> {
        let values = self
            .pluck_value()
            .await?
            .into_iter()
            .collect::<std::collections::BTreeSet<_>>();
        Ok(values.into_iter().collect())
    }

    pub async fn first_value(mut self) -> anyhow::Result<Option<String>> {
        self.limit = Some(1);
        Ok(self.pluck_value().await?.into_iter().next())
    }

    pub async fn only_value(mut self) -> anyhow::Result<String> {
        self.limit = Some(2);
        let mut values = self.pluck_value().await?;
        match values.len() {
            1 => Ok(values.remove(0)),
            0 => anyhow::bail!("expected exactly one LocaleSetting.value value, found none"),
            _ => anyhow::bail!("expected exactly one LocaleSetting.value value, found multiple"),
        }
    }

    pub async fn count_by_tenant_id_and_locale(
        self,
    ) -> anyhow::Result<Vec<((String, String), u64)>> {
        let db = self.repo.read_db_from(self.read_source)?;
        let rows = self
            .build_filter_select()
            .select_only()
            .column(Column::TenantId)
            .column(Column::Locale)
            .column_as(Column::TenantId.count(), "roze_count")
            .group_by(Column::TenantId)
            .group_by(Column::Locale)
            .into_tuple::<(String, String, i64)>()
            .all(&db)
            .await?;
        Ok(rows
            .into_iter()
            .map(|(left, right, count)| ((left, right), count as u64))
            .collect())
    }

    pub async fn count_by_tenant_id_and_value(
        self,
    ) -> anyhow::Result<Vec<((String, String), u64)>> {
        let db = self.repo.read_db_from(self.read_source)?;
        let rows = self
            .build_filter_select()
            .select_only()
            .column(Column::TenantId)
            .column(Column::Value)
            .column_as(Column::TenantId.count(), "roze_count")
            .group_by(Column::TenantId)
            .group_by(Column::Value)
            .into_tuple::<(String, String, i64)>()
            .all(&db)
            .await?;
        Ok(rows
            .into_iter()
            .map(|(left, right, count)| ((left, right), count as u64))
            .collect())
    }

    pub async fn count_by_locale_and_value(self) -> anyhow::Result<Vec<((String, String), u64)>> {
        let db = self.repo.read_db_from(self.read_source)?;
        let rows = self
            .build_filter_select()
            .select_only()
            .column(Column::Locale)
            .column(Column::Value)
            .column_as(Column::Locale.count(), "roze_count")
            .group_by(Column::Locale)
            .group_by(Column::Value)
            .into_tuple::<(String, String, i64)>()
            .all(&db)
            .await?;
        Ok(rows
            .into_iter()
            .map(|(left, right, count)| ((left, right), count as u64))
            .collect())
    }

    pub async fn first(self) -> anyhow::Result<Option<Model>> {
        let db = self.repo.read_db_from(self.read_source)?;
        Ok(self.build_select().one(&db).await?)
    }

    pub async fn only(mut self) -> anyhow::Result<Model> {
        self.limit = Some(2);
        let mut items = self.all().await?;
        match items.len() {
            1 => Ok(items.remove(0)),
            0 => anyhow::bail!("expected exactly one LocaleSetting row, found none"),
            _ => anyhow::bail!("expected exactly one LocaleSetting row, found multiple"),
        }
    }

    pub async fn page(self) -> anyhow::Result<LocaleSettingPage> {
        let db = self.repo.read_db_from(self.read_source)?;
        let (page, page_size) = self.page.unwrap_or((1, 20));
        let page = if page == 0 { 1 } else { page };
        let page_size = if page_size == 0 {
            20
        } else {
            page_size.min(500)
        };
        tracing::debug!(
            model = "LocaleSetting",
            backend = "sea_orm",
            source = self.read_source.label(),
            query_type = "page",
            page,
            page_size,
            predicate_count = self.predicates.len(),
            order_count = self.orders.len(),
            "model query executing"
        );
        let total = self.build_filter_select().count(&db).await?;
        let paginator = self.build_select().paginate(&db, page_size);
        let items = paginator.fetch_page(page.saturating_sub(1)).await?;
        Ok(LocaleSettingPage {
            items,
            total,
            page,
            page_size,
        })
    }
}

struct LocaleSettingQueryTerminal;
impl<'repo, 'ctx> roze_orm::Operation<LocaleSettingQuery<'repo, 'ctx>, Vec<Model>, anyhow::Error>
    for LocaleSettingQueryTerminal
{
    fn call<'a>(
        &'a self,
        query: LocaleSettingQuery<'repo, 'ctx>,
    ) -> roze_orm::OperationFuture<'a, Vec<Model>, anyhow::Error>
    where
        LocaleSettingQuery<'repo, 'ctx>: 'a,
        Vec<Model>: 'a,
        anyhow::Error: 'a,
    {
        Box::pin(query.all_unintercepted())
    }
}

pub struct LocaleSettingCreate<'repo, 'ctx> {
    repo: &'repo LocaleSettingRepository<'ctx>,
    hooks:
        Vec<std::sync::Arc<dyn roze_orm::OperationMiddleware<Self, Model, anyhow::Error> + 'repo>>,
    tenant_id: Option<String>,
    locale: Option<String>,
    value: Option<String>,
}

impl<'repo, 'ctx> LocaleSettingCreate<'repo, 'ctx> {
    pub fn new(repo: &'repo LocaleSettingRepository<'ctx>) -> Self {
        Self {
            repo,
            hooks: Vec::new(),
            tenant_id: None,
            locale: None,
            value: None,
        }
    }

    pub fn set_tenant_id(mut self, value: String) -> Self {
        self.tenant_id = Some(value);
        self
    }

    pub fn set_locale(mut self, value: String) -> Self {
        self.locale = Some(value);
        self
    }

    pub fn set_value(mut self, value: String) -> Self {
        self.value = Some(value);
        self
    }

    pub fn hook<H>(mut self, hook: H) -> Self
    where
        H: roze_orm::OperationMiddleware<Self, Model, anyhow::Error> + 'repo,
    {
        self.hooks.push(std::sync::Arc::new(hook));
        self
    }

    pub fn policy<I, D>(mut self, rules: I, deny_by_default: D) -> Self
    where
        I: IntoIterator<
            Item = std::sync::Arc<dyn roze_orm::Policy<Self, Error = anyhow::Error> + 'repo>,
        >,
        D: Fn() -> anyhow::Error + Send + Sync + 'repo,
    {
        self.hooks
            .push(std::sync::Arc::new(roze_orm::PolicyMiddleware::new(
                rules,
                deny_by_default,
            )));
        self
    }

    pub fn mixin<M>(self, mixin: M) -> Self
    where
        M: roze_orm::OperationMixin<Self>,
    {
        mixin.apply(self)
    }

    pub async fn save(mut self) -> anyhow::Result<Model> {
        let hooks = std::mem::take(&mut self.hooks);
        roze_orm::execute_chain(&LocaleSettingCreateTerminal, &hooks, self).await
    }

    async fn save_unhooked(self) -> anyhow::Result<Model> {
        if let Some(value) = self.tenant_id.as_ref() {
            if value.is_empty() {
                anyhow::bail!("tenant_id validation failed: must not be empty");
            }
            if value.chars().count() > 64 {
                anyhow::bail!("tenant_id validation failed: length must be at most 64");
            }
        }
        if let Some(value) = self.locale.as_ref() {
            if value.is_empty() {
                anyhow::bail!("locale validation failed: must not be empty");
            }
            if value.chars().count() > 32 {
                anyhow::bail!("locale validation failed: length must be at most 32");
            }
        }
        if let Some(value) = self.value.as_ref() {
            if value.chars().count() > 500 {
                anyhow::bail!("value validation failed: length must be at most 500");
            }
        }
        let db = self.repo.write_db()?;
        let active = ActiveModel {
            tenant_id: Set(self.tenant_id.ok_or_else(|| {
                anyhow::anyhow!("missing required field `tenant_id` for LocaleSetting create")
            })?),
            locale: Set(self.locale.ok_or_else(|| {
                anyhow::anyhow!("missing required field `locale` for LocaleSetting create")
            })?),
            value: Set(self.value.ok_or_else(|| {
                anyhow::anyhow!("missing required field `value` for LocaleSetting create")
            })?),
        };
        let insert_key = (
            active.tenant_id.clone().unwrap(),
            active.locale.clone().unwrap(),
        );
        Entity::insert(active).exec_without_returning(&db).await?;
        let inserted = Entity::find_by_id(insert_key)
            .one(&db)
            .await?
            .ok_or_else(|| anyhow::anyhow!("inserted LocaleSetting could not be reloaded"))?;
        Ok(inserted)
    }
}

struct LocaleSettingCreateTerminal;
impl<'repo, 'ctx> roze_orm::Operation<LocaleSettingCreate<'repo, 'ctx>, Model, anyhow::Error>
    for LocaleSettingCreateTerminal
{
    fn call<'a>(
        &'a self,
        mutation: LocaleSettingCreate<'repo, 'ctx>,
    ) -> roze_orm::OperationFuture<'a, Model, anyhow::Error>
    where
        LocaleSettingCreate<'repo, 'ctx>: 'a,
        Model: 'a,
        anyhow::Error: 'a,
    {
        Box::pin(mutation.save_unhooked())
    }
}

pub struct LocaleSettingUpdate<'repo, 'ctx> {
    repo: &'repo LocaleSettingRepository<'ctx>,
    hooks:
        Vec<std::sync::Arc<dyn roze_orm::OperationMiddleware<Self, Model, anyhow::Error> + 'repo>>,
    key: LocaleSettingKey,
    value: Option<String>,
}

impl<'repo, 'ctx> LocaleSettingUpdate<'repo, 'ctx> {
    pub fn new(repo: &'repo LocaleSettingRepository<'ctx>, key: LocaleSettingKey) -> Self {
        Self {
            repo,
            hooks: Vec::new(),
            key,
            value: None,
        }
    }

    pub fn set_value(mut self, value: String) -> Self {
        self.value = Some(value);
        self
    }

    pub fn hook<H>(mut self, hook: H) -> Self
    where
        H: roze_orm::OperationMiddleware<Self, Model, anyhow::Error> + 'repo,
    {
        self.hooks.push(std::sync::Arc::new(hook));
        self
    }

    pub fn policy<I, D>(mut self, rules: I, deny_by_default: D) -> Self
    where
        I: IntoIterator<
            Item = std::sync::Arc<dyn roze_orm::Policy<Self, Error = anyhow::Error> + 'repo>,
        >,
        D: Fn() -> anyhow::Error + Send + Sync + 'repo,
    {
        self.hooks
            .push(std::sync::Arc::new(roze_orm::PolicyMiddleware::new(
                rules,
                deny_by_default,
            )));
        self
    }

    pub fn mixin<M>(self, mixin: M) -> Self
    where
        M: roze_orm::OperationMixin<Self>,
    {
        mixin.apply(self)
    }

    pub async fn save(mut self) -> anyhow::Result<Model> {
        let hooks = std::mem::take(&mut self.hooks);
        roze_orm::execute_chain(&LocaleSettingUpdateTerminal, &hooks, self).await
    }

    async fn save_unhooked(self) -> anyhow::Result<Model> {
        if let Some(value) = self.value.as_ref() {
            if value.chars().count() > 500 {
                anyhow::bail!("value validation failed: length must be at most 500");
            }
        }
        let db = self.repo.write_db()?;
        let mut active = ActiveModel {
            tenant_id: Set(self.key.tenant_id),
            locale: Set(self.key.locale),
            ..std::default::Default::default()
        };
        if let Some(value) = self.value {
            active.value = Set(value);
        }
        let updated = active.update(&db).await?;
        Ok(updated)
    }
}

struct LocaleSettingUpdateTerminal;
impl<'repo, 'ctx> roze_orm::Operation<LocaleSettingUpdate<'repo, 'ctx>, Model, anyhow::Error>
    for LocaleSettingUpdateTerminal
{
    fn call<'a>(
        &'a self,
        mutation: LocaleSettingUpdate<'repo, 'ctx>,
    ) -> roze_orm::OperationFuture<'a, Model, anyhow::Error>
    where
        LocaleSettingUpdate<'repo, 'ctx>: 'a,
        Model: 'a,
        anyhow::Error: 'a,
    {
        Box::pin(mutation.save_unhooked())
    }
}

pub struct LocaleSettingDelete<'repo, 'ctx> {
    repo: &'repo LocaleSettingRepository<'ctx>,
    hooks: Vec<
        std::sync::Arc<
            dyn roze_orm::OperationMiddleware<Self, DeleteResult, anyhow::Error> + 'repo,
        >,
    >,
    key: LocaleSettingKey,
}

impl<'repo, 'ctx> LocaleSettingDelete<'repo, 'ctx> {
    pub fn new(repo: &'repo LocaleSettingRepository<'ctx>, key: LocaleSettingKey) -> Self {
        Self {
            repo,
            hooks: Vec::new(),
            key,
        }
    }

    pub fn hook<H>(mut self, hook: H) -> Self
    where
        H: roze_orm::OperationMiddleware<Self, DeleteResult, anyhow::Error> + 'repo,
    {
        self.hooks.push(std::sync::Arc::new(hook));
        self
    }

    pub fn policy<I, D>(mut self, rules: I, deny_by_default: D) -> Self
    where
        I: IntoIterator<
            Item = std::sync::Arc<dyn roze_orm::Policy<Self, Error = anyhow::Error> + 'repo>,
        >,
        D: Fn() -> anyhow::Error + Send + Sync + 'repo,
    {
        self.hooks
            .push(std::sync::Arc::new(roze_orm::PolicyMiddleware::new(
                rules,
                deny_by_default,
            )));
        self
    }

    pub fn mixin<M>(self, mixin: M) -> Self
    where
        M: roze_orm::OperationMixin<Self>,
    {
        mixin.apply(self)
    }

    pub async fn exec(mut self) -> anyhow::Result<DeleteResult> {
        let hooks = std::mem::take(&mut self.hooks);
        roze_orm::execute_chain(&LocaleSettingDeleteTerminal, &hooks, self).await
    }

    async fn exec_unhooked(self) -> anyhow::Result<DeleteResult> {
        self.repo.delete_by_key(self.key).await
    }
}

struct LocaleSettingDeleteTerminal;
impl<'repo, 'ctx> roze_orm::Operation<LocaleSettingDelete<'repo, 'ctx>, DeleteResult, anyhow::Error>
    for LocaleSettingDeleteTerminal
{
    fn call<'a>(
        &'a self,
        mutation: LocaleSettingDelete<'repo, 'ctx>,
    ) -> roze_orm::OperationFuture<'a, DeleteResult, anyhow::Error>
    where
        LocaleSettingDelete<'repo, 'ctx>: 'a,
        DeleteResult: 'a,
        anyhow::Error: 'a,
    {
        Box::pin(mutation.exec_unhooked())
    }
}

pub struct LocaleSettingUpdateMany<'repo, 'ctx> {
    repo: &'repo LocaleSettingRepository<'ctx>,
    hooks: Vec<
        std::sync::Arc<dyn roze_orm::OperationMiddleware<Self, Vec<Model>, anyhow::Error> + 'repo>,
    >,
    atomic_hooks:
        Vec<std::sync::Arc<dyn roze_orm::OperationMiddleware<Self, u64, anyhow::Error> + 'repo>>,
    predicates: Vec<LocaleSettingPredicate>,
    value: Option<String>,
}

impl<'repo, 'ctx> LocaleSettingUpdateMany<'repo, 'ctx> {
    pub fn new(repo: &'repo LocaleSettingRepository<'ctx>) -> Self {
        Self {
            repo,
            hooks: Vec::new(),
            atomic_hooks: Vec::new(),
            predicates: Vec::new(),
            value: None,
        }
    }

    pub fn intercept<F>(self, interceptor: F) -> Self
    where
        F: FnOnce(Self) -> Self,
    {
        interceptor(self)
    }

    pub fn policy<I, D>(mut self, rules: I, deny_by_default: D) -> Self
    where
        I: IntoIterator<
            Item = std::sync::Arc<dyn roze_orm::Policy<Self, Error = anyhow::Error> + 'repo>,
        >,
        D: Fn() -> anyhow::Error + Send + Sync + 'repo,
    {
        let policy = roze_orm::PolicyMiddleware::new(rules, deny_by_default);
        self.hooks.push(std::sync::Arc::new(policy.clone()));
        self.atomic_hooks.push(std::sync::Arc::new(policy));
        self
    }

    pub fn mixin<M>(self, mixin: M) -> Self
    where
        M: roze_orm::OperationMixin<Self>,
    {
        mixin.apply(self)
    }

    pub fn where_(mut self, predicate: LocaleSettingPredicate) -> Self {
        self.predicates.push(predicate);
        self
    }

    pub fn where_all<I>(mut self, predicates: I) -> Self
    where
        I: IntoIterator<Item = LocaleSettingPredicate>,
    {
        self.predicates.extend(predicates);
        self
    }

    pub fn where_any<I>(mut self, predicates: I) -> Self
    where
        I: IntoIterator<Item = LocaleSettingPredicate>,
    {
        let predicates = predicates.into_iter().collect::<Vec<_>>();
        if !predicates.is_empty() {
            self.predicates.push(LocaleSettingPredicate::Or(predicates));
        }
        self
    }

    pub fn where_not(mut self, predicate: LocaleSettingPredicate) -> Self {
        self.predicates
            .push(LocaleSettingPredicate::Not(Box::new(predicate)));
        self
    }

    pub fn where_none<I>(mut self, predicates: I) -> Self
    where
        I: IntoIterator<Item = LocaleSettingPredicate>,
    {
        let predicates = predicates.into_iter().collect::<Vec<_>>();
        if !predicates.is_empty() {
            self.predicates.push(LocaleSettingPredicate::Not(Box::new(
                LocaleSettingPredicate::Or(predicates),
            )));
        }
        self
    }

    pub fn set_value(mut self, value: String) -> Self {
        self.value = Some(value);
        self
    }

    pub fn hook<H>(mut self, hook: H) -> Self
    where
        H: roze_orm::OperationMiddleware<Self, Vec<Model>, anyhow::Error> + 'repo,
    {
        self.hooks.push(std::sync::Arc::new(hook));
        self
    }

    pub fn atomic_hook<H>(mut self, hook: H) -> Self
    where
        H: roze_orm::OperationMiddleware<Self, u64, anyhow::Error> + 'repo,
    {
        self.atomic_hooks.push(std::sync::Arc::new(hook));
        self
    }

    /// Executes one conditional SQL UPDATE and returns its affected-row count.
    pub async fn execute(mut self) -> anyhow::Result<UpdateResult> {
        struct ConditionalUpdateTerminal;
        impl<'repo, 'ctx>
            roze_orm::Operation<LocaleSettingUpdateMany<'repo, 'ctx>, u64, anyhow::Error>
            for ConditionalUpdateTerminal
        {
            fn call<'call>(
                &'call self,
                mutation: LocaleSettingUpdateMany<'repo, 'ctx>,
            ) -> roze_orm::OperationFuture<'call, u64, anyhow::Error>
            where
                LocaleSettingUpdateMany<'repo, 'ctx>: 'call,
                u64: 'call,
                anyhow::Error: 'call,
            {
                Box::pin(mutation.execute_unhooked())
            }
        }
        let hooks = std::mem::take(&mut self.atomic_hooks);
        let rows_affected =
            roze_orm::execute_chain(&ConditionalUpdateTerminal, &hooks, self).await?;
        Ok(UpdateResult { rows_affected })
    }

    async fn execute_unhooked(self) -> anyhow::Result<u64> {
        if let Some(value) = self.value.as_ref() {
            if value.chars().count() > 500 {
                anyhow::bail!("value validation failed: length must be at most 500");
            }
        }
        if self.value.is_none() {
            anyhow::bail!("conditional update requires at least one field assignment");
        }
        let db = self.repo.write_db()?;
        let mut update = Entity::update_many();
        for predicate in &self.predicates {
            update = update.filter(LocaleSettingQuery::predicate_condition(predicate));
        }
        if let Some(value) = self.value.as_ref() {
            update = update.col_expr(Column::Value, Expr::value(value.clone()));
        }
        let result = update.exec(&db).await?;
        Ok(result.rows_affected)
    }

    pub async fn save(mut self) -> anyhow::Result<Vec<Model>> {
        let hooks = std::mem::take(&mut self.hooks);
        roze_orm::execute_chain(&LocaleSettingUpdateManyTerminal, &hooks, self).await
    }

    async fn save_unhooked(self) -> anyhow::Result<Vec<Model>> {
        if let Some(value) = self.value.as_ref() {
            if value.chars().count() > 500 {
                anyhow::bail!("value validation failed: length must be at most 500");
            }
        }
        let mut query = self.repo.query();
        for predicate in &self.predicates {
            query = query.where_(predicate.clone());
        }
        let items = query.all().await?;
        let mut updated = Vec::with_capacity(items.len());
        for item in items {
            let mut update = self.repo.update_one(LocaleSettingKey {
                tenant_id: item.tenant_id.clone(),
                locale: item.locale.clone(),
            });
            if let Some(value) = self.value.as_ref() {
                update = update.set_value(value.clone());
            }
            updated.push(update.save().await?);
        }
        Ok(updated)
    }
}

struct LocaleSettingUpdateManyTerminal;
impl<'repo, 'ctx>
    roze_orm::Operation<LocaleSettingUpdateMany<'repo, 'ctx>, Vec<Model>, anyhow::Error>
    for LocaleSettingUpdateManyTerminal
{
    fn call<'a>(
        &'a self,
        mutation: LocaleSettingUpdateMany<'repo, 'ctx>,
    ) -> roze_orm::OperationFuture<'a, Vec<Model>, anyhow::Error>
    where
        LocaleSettingUpdateMany<'repo, 'ctx>: 'a,
        Vec<Model>: 'a,
        anyhow::Error: 'a,
    {
        Box::pin(mutation.save_unhooked())
    }
}

pub struct LocaleSettingDeleteMany<'repo, 'ctx> {
    repo: &'repo LocaleSettingRepository<'ctx>,
    hooks: Vec<std::sync::Arc<dyn roze_orm::OperationMiddleware<Self, u64, anyhow::Error> + 'repo>>,
    predicates: Vec<LocaleSettingPredicate>,
}

impl<'repo, 'ctx> LocaleSettingDeleteMany<'repo, 'ctx> {
    pub fn new(repo: &'repo LocaleSettingRepository<'ctx>) -> Self {
        Self {
            repo,
            hooks: Vec::new(),
            predicates: Vec::new(),
        }
    }

    pub fn where_(mut self, predicate: LocaleSettingPredicate) -> Self {
        self.predicates.push(predicate);
        self
    }

    pub fn where_all<I>(mut self, predicates: I) -> Self
    where
        I: IntoIterator<Item = LocaleSettingPredicate>,
    {
        self.predicates.extend(predicates);
        self
    }

    pub fn where_any<I>(mut self, predicates: I) -> Self
    where
        I: IntoIterator<Item = LocaleSettingPredicate>,
    {
        let predicates = predicates.into_iter().collect::<Vec<_>>();
        if !predicates.is_empty() {
            self.predicates.push(LocaleSettingPredicate::Or(predicates));
        }
        self
    }

    pub fn where_not(mut self, predicate: LocaleSettingPredicate) -> Self {
        self.predicates
            .push(LocaleSettingPredicate::Not(Box::new(predicate)));
        self
    }

    pub fn where_none<I>(mut self, predicates: I) -> Self
    where
        I: IntoIterator<Item = LocaleSettingPredicate>,
    {
        let predicates = predicates.into_iter().collect::<Vec<_>>();
        if !predicates.is_empty() {
            self.predicates.push(LocaleSettingPredicate::Not(Box::new(
                LocaleSettingPredicate::Or(predicates),
            )));
        }
        self
    }

    pub fn hook<H>(mut self, hook: H) -> Self
    where
        H: roze_orm::OperationMiddleware<Self, u64, anyhow::Error> + 'repo,
    {
        self.hooks.push(std::sync::Arc::new(hook));
        self
    }

    pub fn policy<I, D>(mut self, rules: I, deny_by_default: D) -> Self
    where
        I: IntoIterator<
            Item = std::sync::Arc<dyn roze_orm::Policy<Self, Error = anyhow::Error> + 'repo>,
        >,
        D: Fn() -> anyhow::Error + Send + Sync + 'repo,
    {
        self.hooks
            .push(std::sync::Arc::new(roze_orm::PolicyMiddleware::new(
                rules,
                deny_by_default,
            )));
        self
    }

    pub fn mixin<M>(self, mixin: M) -> Self
    where
        M: roze_orm::OperationMixin<Self>,
    {
        mixin.apply(self)
    }

    pub async fn exec(mut self) -> anyhow::Result<u64> {
        let hooks = std::mem::take(&mut self.hooks);
        roze_orm::execute_chain(&LocaleSettingDeleteManyTerminal, &hooks, self).await
    }

    async fn exec_unhooked(self) -> anyhow::Result<u64> {
        let mut query = self.repo.query();
        for predicate in &self.predicates {
            query = query.where_(predicate.clone());
        }
        let items = query.all().await?;
        let mut rows_affected = 0u64;
        for item in items {
            let result = self
                .repo
                .delete_one(LocaleSettingKey {
                    tenant_id: item.tenant_id.clone(),
                    locale: item.locale.clone(),
                })
                .exec()
                .await?;
            rows_affected += result.rows_affected;
        }
        Ok(rows_affected)
    }
}

struct LocaleSettingDeleteManyTerminal;
impl<'repo, 'ctx> roze_orm::Operation<LocaleSettingDeleteMany<'repo, 'ctx>, u64, anyhow::Error>
    for LocaleSettingDeleteManyTerminal
{
    fn call<'a>(
        &'a self,
        mutation: LocaleSettingDeleteMany<'repo, 'ctx>,
    ) -> roze_orm::OperationFuture<'a, u64, anyhow::Error>
    where
        LocaleSettingDeleteMany<'repo, 'ctx>: 'a,
        u64: 'a,
        anyhow::Error: 'a,
    {
        Box::pin(mutation.exec_unhooked())
    }
}

/// Reusable schema/client mutation hook provider.
/// Providers are applied in registration order; hooks they add are outermost before hooks added directly to a builder.
pub trait LocaleSettingMutationHooks: Send + Sync {
    fn create<'repo, 'ctx>(
        &self,
        mutation: LocaleSettingCreate<'repo, 'ctx>,
    ) -> LocaleSettingCreate<'repo, 'ctx> {
        mutation
    }
    fn update_one<'repo, 'ctx>(
        &self,
        mutation: LocaleSettingUpdate<'repo, 'ctx>,
    ) -> LocaleSettingUpdate<'repo, 'ctx> {
        mutation
    }
    fn delete_one<'repo, 'ctx>(
        &self,
        mutation: LocaleSettingDelete<'repo, 'ctx>,
    ) -> LocaleSettingDelete<'repo, 'ctx> {
        mutation
    }
    fn update_many<'repo, 'ctx>(
        &self,
        mutation: LocaleSettingUpdateMany<'repo, 'ctx>,
    ) -> LocaleSettingUpdateMany<'repo, 'ctx> {
        mutation
    }
    fn delete_many<'repo, 'ctx>(
        &self,
        mutation: LocaleSettingDeleteMany<'repo, 'ctx>,
    ) -> LocaleSettingDeleteMany<'repo, 'ctx> {
        mutation
    }
}

pub fn escape_like_pattern(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '\\' | '%' | '_' => {
                escaped.push('\\');
                escaped.push(ch);
            }
            _ => escaped.push(ch),
        }
    }
    escaped
}

pub fn contains_like_pattern(value: &str) -> String {
    format!("%{}%", escape_like_pattern(value))
}

pub struct LocaleSettingRepository<'a> {
    ctx: &'a ServiceContext,
    transaction: Option<&'a DatabaseTransaction>,
    pending_invalidations: Option<&'a std::sync::Mutex<Vec<String>>>,
    mutation_hooks: Vec<&'a dyn LocaleSettingMutationHooks>,
}

impl<'a> LocaleSettingRepository<'a> {
    pub fn new(ctx: &'a ServiceContext) -> Self {
        Self {
            ctx,
            transaction: None,
            pending_invalidations: None,
            mutation_hooks: Vec::new(),
        }
    }

    pub(crate) fn new_in_transaction(
        ctx: &'a ServiceContext,
        transaction: &'a DatabaseTransaction,
        pending_invalidations: &'a std::sync::Mutex<Vec<String>>,
    ) -> Self {
        Self {
            ctx,
            transaction: Some(transaction),
            pending_invalidations: Some(pending_invalidations),
            mutation_hooks: Vec::new(),
        }
    }

    pub fn with_mutation_hooks(mut self, hooks: &'a dyn LocaleSettingMutationHooks) -> Self {
        self.mutation_hooks.push(hooks);
        self
    }

    fn read_database(&self) -> anyhow::Result<&DatabaseConnection> {
        self.ctx.read_db()
    }

    fn write_database(&self) -> anyhow::Result<&DatabaseConnection> {
        self.ctx.write_db()
    }

    fn read_db(&self) -> anyhow::Result<ModelConnection<'_>> {
        if let Some(transaction) = self.transaction {
            Ok(ModelConnection::Transaction(transaction))
        } else {
            Ok(ModelConnection::Database(self.read_database()?))
        }
    }

    fn write_db(&self) -> anyhow::Result<ModelConnection<'_>> {
        if let Some(transaction) = self.transaction {
            Ok(ModelConnection::Transaction(transaction))
        } else {
            Ok(ModelConnection::Database(self.write_database()?))
        }
    }

    fn read_db_from(&self, source: roze_orm::ReadSource) -> anyhow::Result<ModelConnection<'_>> {
        match source {
            roze_orm::ReadSource::Replica => self.read_db(),
            roze_orm::ReadSource::Primary => self.write_db(),
        }
    }

    pub async fn transaction<F, T>(&self, func: F) -> Result<T, DbErr>
    where
        F: for<'tx> FnOnce(
                &'tx DatabaseTransaction,
            ) -> std::pin::Pin<
                Box<dyn std::future::Future<Output = Result<T, DbErr>> + Send + 'tx>,
            > + Send,
        T: Send,
    {
        let db = self
            .write_database()
            .map_err(|err| DbErr::Custom(err.to_string()))?;
        tracing::debug!(
            backend = "sea_orm",
            phase = "begin",
            "model transaction phase"
        );
        let result = db
            .transaction::<_, T, DbErr>(func)
            .await
            .map_err(|err| match err {
                TransactionError::Connection(err) | TransactionError::Transaction(err) => err,
            });
        tracing::debug!(
            backend = "sea_orm",
            phase = if result.is_ok() { "commit" } else { "rollback" },
            "model transaction phase"
        );
        result
    }

    pub fn table_name() -> &'static str {
        "locale_settings"
    }

    pub async fn seed_fixtures(&self, count: u64) -> anyhow::Result<Vec<Model>> {
        let mut seeded = Vec::with_capacity(count as usize);
        for index in 0..count {
            seeded.push(self.insert(Model::fixture(index)).await?);
        }
        Ok(seeded)
    }

    pub fn create(&self) -> LocaleSettingCreate<'_, 'a> {
        self.mutation_hooks
            .iter()
            .fold(LocaleSettingCreate::new(self), |mutation, hooks| {
                hooks.create(mutation)
            })
    }

    pub fn update_one(&self, key: LocaleSettingKey) -> LocaleSettingUpdate<'_, 'a> {
        self.mutation_hooks
            .iter()
            .fold(LocaleSettingUpdate::new(self, key), |mutation, hooks| {
                hooks.update_one(mutation)
            })
    }

    pub fn delete_one(&self, key: LocaleSettingKey) -> LocaleSettingDelete<'_, 'a> {
        self.mutation_hooks
            .iter()
            .fold(LocaleSettingDelete::new(self, key), |mutation, hooks| {
                hooks.delete_one(mutation)
            })
    }

    pub fn update_many(&self) -> LocaleSettingUpdateMany<'_, 'a> {
        self.mutation_hooks
            .iter()
            .fold(LocaleSettingUpdateMany::new(self), |mutation, hooks| {
                hooks.update_many(mutation)
            })
    }

    pub fn update_where(&self) -> LocaleSettingUpdateMany<'_, 'a> {
        self.update_many()
    }

    pub fn delete_many(&self) -> LocaleSettingDeleteMany<'_, 'a> {
        self.mutation_hooks
            .iter()
            .fold(LocaleSettingDeleteMany::new(self), |mutation, hooks| {
                hooks.delete_many(mutation)
            })
    }

    pub fn query(&self) -> LocaleSettingQuery<'_, 'a> {
        LocaleSettingQuery::new(self)
    }

    pub async fn count(&self) -> anyhow::Result<u64> {
        self.query().count().await
    }

    pub async fn list_page(&self, page: u64, page_size: u64) -> anyhow::Result<LocaleSettingPage> {
        self.query().paginate(page, page_size).page().await
    }

    pub async fn find_by_key(&self, key: LocaleSettingKey) -> anyhow::Result<Option<Model>> {
        let db = self.read_db()?;
        Ok(Entity::find_by_id((key.tenant_id, key.locale))
            .one(&db)
            .await?)
    }

    pub async fn delete_by_key(&self, key: LocaleSettingKey) -> anyhow::Result<DeleteResult> {
        let db = self.write_db()?;
        Ok(Entity::delete_by_id((key.tenant_id, key.locale))
            .exec(&db)
            .await?)
    }

    pub async fn update_by_key(
        &self,
        key: LocaleSettingKey,
        mut model: Model,
    ) -> anyhow::Result<Model> {
        model.tenant_id = key.tenant_id;
        model.locale = key.locale;
        self.update(model).await
    }

    pub async fn delete_many_by_keys(
        &self,
        keys: Vec<LocaleSettingKey>,
    ) -> anyhow::Result<DeleteResult> {
        let mut rows_affected = 0u64;
        for key in keys {
            rows_affected += self.delete_by_key(key).await?.rows_affected;
        }
        Ok(DeleteResult { rows_affected })
    }

    pub async fn list(&self) -> anyhow::Result<Vec<Model>> {
        let db = self.read_db()?;
        let select = Entity::find();
        Ok(select.all(&db).await?)
    }

    pub async fn insert(&self, model: Model) -> anyhow::Result<Model> {
        let db = self.write_db()?;
        let active: ActiveModel = model.into_active_model();
        let insert_key = (
            active.tenant_id.clone().unwrap(),
            active.locale.clone().unwrap(),
        );
        Entity::insert(active).exec_without_returning(&db).await?;
        let inserted = Entity::find_by_id(insert_key)
            .one(&db)
            .await?
            .ok_or_else(|| anyhow::anyhow!("inserted LocaleSetting could not be reloaded"))?;
        Ok(inserted)
    }

    pub async fn upsert(&self, model: Model) -> anyhow::Result<Model> {
        let db = self.write_db()?;
        let upsert_key = (model.tenant_id.clone(), model.locale.clone());
        let active: ActiveModel = model.into_active_model();
        Entity::insert(active)
            .on_conflict(
                OnConflict::columns([Column::TenantId, Column::Locale])
                    .update_columns([Column::Value])
                    .to_owned(),
            )
            .exec(&db)
            .await?;
        let saved = Entity::find_by_id(upsert_key)
            .one(&db)
            .await?
            .ok_or_else(|| anyhow::anyhow!("upserted LocaleSetting could not be reloaded"))?;
        Ok(saved)
    }

    pub async fn insert_many(&self, models: Vec<Model>) -> anyhow::Result<()> {
        if models.is_empty() {
            return Ok(());
        }
        let db = self.write_db()?;
        let active_models = models
            .into_iter()
            .map(IntoActiveModel::into_active_model)
            .collect::<Vec<_>>();
        Entity::insert_many(active_models).exec(&db).await?;
        Ok(())
    }

    pub async fn delete_many_by_ids(&self, ids: Vec<String>) -> anyhow::Result<DeleteResult> {
        if ids.is_empty() {
            return Ok(DeleteResult { rows_affected: 0 });
        }
        let db = self.write_db()?;
        let result = Entity::delete_many()
            .filter(Column::TenantId.is_in(ids.clone()))
            .exec(&db)
            .await?;
        Ok(result)
    }

    pub async fn update(&self, model: Model) -> anyhow::Result<Model> {
        let db = self.write_db()?;
        let active: ActiveModel = model.into_active_model();
        let updated = active.update(&db).await?;
        Ok(updated)
    }
}
