// @generated by rozectl. DO NOT EDIT.
#![allow(dead_code)]

pub const LOCALE_SETTING_TABLE: &str = "locale_settings";
pub const LOCALE_SETTING_FIELDS: &[LocaleSettingField] = &[
    LocaleSettingField::TenantId,
    LocaleSettingField::Locale,
    LocaleSettingField::Value,
];

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum LocaleSettingField {
    TenantId,
    Locale,
    Value,
}

impl LocaleSettingField {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::TenantId => "tenant_id",
            Self::Locale => "locale",
            Self::Value => "value",
        }
    }
}
