// @generated by rozectl. DO NOT EDIT.
#![allow(dead_code)]

pub const MEMBERSHIP_TABLE: &str = "memberships";
pub const MEMBERSHIP_FIELDS: &[MembershipField] = &[
    MembershipField::Id,
    MembershipField::UserId,
    MembershipField::GroupId,
    MembershipField::Role,
    MembershipField::JoinedAt,
];

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MembershipField {
    Id,
    UserId,
    GroupId,
    Role,
    JoinedAt,
}

impl MembershipField {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Id => "id",
            Self::UserId => "user_id",
            Self::GroupId => "group_id",
            Self::Role => "role",
            Self::JoinedAt => "joined_at",
        }
    }
}
