// @generated by rozectl. DO NOT EDIT.
// @roze-model-orm: sea-orm
#![allow(dead_code, unused_imports)]

use crate::svc::ServiceContext;

pub mod client;
pub use client::ModelClient;
pub mod user;
pub mod user_ext;
pub mod user_fields;
pub use user::{
    ActiveModel as UserActiveModel, Entity as UserEntity, Model as UserModel, UserCreate,
    UserDelete, UserDeleteMany, UserMutationHooks, UserOrder, UserPage, UserPredicate, UserQuery,
    UserRepository, UserUpdate, UserUpdateMany,
};
pub use user_fields::{UserField, USER_TABLE};
pub mod pet;
pub mod pet_ext;
pub mod pet_fields;
pub use pet::{
    ActiveModel as PetActiveModel, Entity as PetEntity, Model as PetModel, PetCreate, PetDelete,
    PetDeleteMany, PetMutationHooks, PetOrder, PetPage, PetPredicate, PetQuery, PetRepository,
    PetUpdate, PetUpdateMany,
};
pub use pet_fields::{PetField, PET_TABLE};

pub async fn configure_context(ctx: ServiceContext) -> anyhow::Result<ServiceContext> {
    Ok(ctx)
}

impl ServiceContext {
    pub fn model(&self) -> ModelClient<'_> {
        ModelClient::new(self)
    }
}
