// @generated by rozectl. DO NOT EDIT.
// @roze-model-orm: sea-orm
#![allow(dead_code, unused_imports)]

use crate::svc::ServiceContext;

pub mod client;
pub use client::ModelClient;
pub mod user;
pub mod user_ext;
pub mod user_fields;
pub use user::{
    ActiveModel as UserActiveModel, Entity as UserEntity, Model as UserModel, UserCreate,
    UserDelete, UserDeleteMany, UserMutationHooks, UserOrder, UserPage, UserPredicate, UserQuery,
    UserRepository, UserUpdate, UserUpdateMany,
};
pub use user_fields::{UserField, USER_TABLE};
pub mod pet;
pub mod pet_ext;
pub mod pet_fields;
pub use pet::{
    ActiveModel as PetActiveModel, Entity as PetEntity, Model as PetModel, PetCreate, PetDelete,
    PetDeleteMany, PetMutationHooks, PetOrder, PetPage, PetPredicate, PetQuery, PetRepository,
    PetUpdate, PetUpdateMany,
};
pub use pet_fields::{PetField, PET_TABLE};
pub mod group;
pub mod group_ext;
pub mod group_fields;
pub use group::{
    ActiveModel as GroupActiveModel, Entity as GroupEntity, GroupCreate, GroupDelete,
    GroupDeleteMany, GroupMutationHooks, GroupOrder, GroupPage, GroupPredicate, GroupQuery,
    GroupRepository, GroupUpdate, GroupUpdateMany, Model as GroupModel,
};
pub use group_fields::{GroupField, GROUP_TABLE};
pub mod membership;
pub mod membership_ext;
pub mod membership_fields;
pub use membership::{
    ActiveModel as MembershipActiveModel, Entity as MembershipEntity, MembershipCreate,
    MembershipDelete, MembershipDeleteMany, MembershipMutationHooks, MembershipOrder,
    MembershipPage, MembershipPredicate, MembershipQuery, MembershipRepository, MembershipUpdate,
    MembershipUpdateMany, Model as MembershipModel,
};
pub use membership_fields::{MembershipField, MEMBERSHIP_TABLE};
pub mod project;
pub mod project_ext;
pub mod project_fields;
pub use project::{
    ActiveModel as ProjectActiveModel, Entity as ProjectEntity, Model as ProjectModel,
    ProjectCreate, ProjectDelete, ProjectDeleteMany, ProjectMutationHooks, ProjectOrder,
    ProjectPage, ProjectPredicate, ProjectQuery, ProjectRepository, ProjectUpdate,
    ProjectUpdateMany,
};
pub use project_fields::{ProjectField, PROJECT_TABLE};

pub async fn configure_context(ctx: ServiceContext) -> anyhow::Result<ServiceContext> {
    Ok(ctx)
}

impl ServiceContext {
    pub fn model(&self) -> ModelClient<'_> {
        ModelClient::new(self)
    }
}
