// @generated by rozectl. DO NOT EDIT.
#![allow(dead_code)]

pub const PET_TABLE: &str = "pets";
pub const PET_FIELDS: &[PetField] = &[
    PetField::Id,
    PetField::OwnerId,
    PetField::Name,
    PetField::Species,
];

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum PetField {
    Id,
    OwnerId,
    Name,
    Species,
}

impl PetField {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Id => "id",
            Self::OwnerId => "owner_id",
            Self::Name => "name",
            Self::Species => "species",
        }
    }
}
