// @generated by rozectl. DO NOT EDIT.
#![allow(dead_code)]

pub const PROJECT_TABLE: &str = "projects";
pub const PROJECT_FIELDS: &[ProjectField] = &[
    ProjectField::Id,
    ProjectField::TenantId,
    ProjectField::Name,
    ProjectField::Description,
    ProjectField::Version,
    ProjectField::DeletedAt,
    ProjectField::CreatedAt,
    ProjectField::UpdatedAt,
];

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ProjectField {
    Id,
    TenantId,
    Name,
    Description,
    Version,
    DeletedAt,
    CreatedAt,
    UpdatedAt,
}

impl ProjectField {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Id => "id",
            Self::TenantId => "tenant_id",
            Self::Name => "name",
            Self::Description => "description",
            Self::Version => "version",
            Self::DeletedAt => "deleted_at",
            Self::CreatedAt => "created_at",
            Self::UpdatedAt => "updated_at",
        }
    }
}
