// @generated by rozectl. DO NOT EDIT.
#![allow(dead_code)]

pub const SCALAR_FIXTURE_TABLE: &str = "scalar_fixtures";
pub const SCALAR_FIXTURE_FIELDS: &[ScalarFixtureField] = &[
    ScalarFixtureField::Id,
    ScalarFixtureField::ExternalId,
    ScalarFixtureField::SmallValue,
    ScalarFixtureField::IntValue,
    ScalarFixtureField::BigValue,
    ScalarFixtureField::FloatValue,
    ScalarFixtureField::DoubleValue,
    ScalarFixtureField::Payload,
    ScalarFixtureField::Metadata,
    ScalarFixtureField::Amount,
    ScalarFixtureField::LocalTime,
    ScalarFixtureField::EventTime,
];

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ScalarFixtureField {
    Id,
    ExternalId,
    SmallValue,
    IntValue,
    BigValue,
    FloatValue,
    DoubleValue,
    Payload,
    Metadata,
    Amount,
    LocalTime,
    EventTime,
}

impl ScalarFixtureField {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Id => "id",
            Self::ExternalId => "external_id",
            Self::SmallValue => "small_value",
            Self::IntValue => "int_value",
            Self::BigValue => "big_value",
            Self::FloatValue => "float_value",
            Self::DoubleValue => "double_value",
            Self::Payload => "payload",
            Self::Metadata => "metadata",
            Self::Amount => "amount",
            Self::LocalTime => "local_time",
            Self::EventTime => "event_time",
        }
    }
}
