// @generated by rozectl. DO NOT EDIT.
#![allow(dead_code)]

pub const USER_TABLE: &str = "users";
pub const USER_FIELDS: &[UserField] = &[
    UserField::Id,
    UserField::Email,
    UserField::Name,
    UserField::Active,
    UserField::CreatedAt,
];

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum UserField {
    Id,
    Email,
    Name,
    Active,
    CreatedAt,
}

impl UserField {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Id => "id",
            Self::Email => "email",
            Self::Name => "name",
            Self::Active => "active",
            Self::CreatedAt => "created_at",
        }
    }
}
