// @generated by roze-ent-codegen. DO NOT EDIT.
#![allow(dead_code)]

use sea_orm::{
    sea_query::{Alias, Expr, Query},
    ConnectionTrait as _, FromQueryResult,
};
use serde::{Deserialize, Serialize};

use crate::svc::ServiceContext;

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, FromQueryResult)]
pub struct UserActivityView {
    pub user_id: i64,
    pub email: String,
    pub name: String,
    pub pet_count: i64,
    pub group_count: i64,
}

pub struct UserActivityViewRepository<'a> {
    ctx: &'a ServiceContext,
}

impl<'a> UserActivityViewRepository<'a> {
    pub fn new(ctx: &'a ServiceContext) -> Self {
        Self { ctx }
    }

    fn select() -> sea_orm::sea_query::SelectStatement {
        let view = Alias::new("user_activity_view");
        Query::select()
            .columns([
                Alias::new("user_id"),
                Alias::new("email"),
                Alias::new("name"),
                Alias::new("pet_count"),
                Alias::new("group_count"),
            ])
            .from(view)
            .to_owned()
    }

    pub async fn all(&self) -> anyhow::Result<Vec<UserActivityView>> {
        let db = self.ctx.read_db()?;
        let backend = db.get_database_backend();
        let statement = backend.build(&Self::select());
        Ok(UserActivityView::find_by_statement(statement)
            .all(db)
            .await?)
    }

    pub async fn find_by_user_id(&self, user_id: i64) -> anyhow::Result<Option<UserActivityView>> {
        let db = self.ctx.read_db()?;
        let backend = db.get_database_backend();
        let mut select = Self::select();
        select.and_where(Expr::col(Alias::new("user_id")).eq(user_id));
        let statement = backend.build(&select);
        Ok(UserActivityView::find_by_statement(statement)
            .one(db)
            .await?)
    }
}

#[cfg(test)]
mod tests {
    #[tokio::test]
    #[ignore = "requires ROZE_ENT_TEST_DATABASE_URL and applied view migrations"]
    async fn generated_view_is_query_only_and_has_real_sql_evidence() -> anyhow::Result<()> {
        let url = std::env::var("ROZE_ENT_TEST_DATABASE_URL")?;
        let config: crate::config::Config = serde_json::from_value(serde_json::json!({
            "name": "roze-ent-view-test",
            "profile": "test",
            "governance": {},
            "database": {
                "mode": "direct",
                "url": url,
                "max_connections": 2,
                "min_connections": 1
            }
        }))?;
        let ctx = crate::svc::ServiceContext::new(config).await?;
        let nonce = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)?
            .as_nanos();
        let user = ctx
            .model()
            .user()
            .create()
            .set_email(format!("view-{nonce}@example.com"))
            .set_name("View user".to_string())
            .save()
            .await?;
        ctx.model()
            .pet()
            .create()
            .set_owner(&user)
            .set_name("View pet".to_string())
            .set_species("other".to_string())
            .save()
            .await?;

        let row = super::UserActivityViewRepository::new(&ctx)
            .find_by_user_id(user.id)
            .await?
            .ok_or_else(|| anyhow::anyhow!("view row missing"))?;
        assert_eq!(row.user_id, user.id);
        assert_eq!(row.pet_count, 1);
        assert_eq!(row.group_count, 0);
        Ok(())
    }
}
