use anyhow::{Context as _, ensure};
use rozectl::generator::model::{
    ExtensionFileOwnership, MODEL_GENERATOR_EXTENSION_API_VERSION, ModelExtensionFile,
    ModelGenerationGraph, ModelGeneratorExtension, ModelOrm,
    generate_model_project_with_extensions,
};
use rozectl::generator::{DependencySource, GenerateMode, GenerateOptions};
use std::{fs, path::PathBuf, time::SystemTime};

struct RozeEntViewExtension;

impl ModelGeneratorExtension for RozeEntViewExtension {
    fn name(&self) -> &'static str {
        "roze-ent-read-only-views"
    }

    fn generate(&self, graph: &ModelGenerationGraph) -> anyhow::Result<Vec<ModelExtensionFile>> {
        ensure!(
            graph.orm == ModelOrm::SeaOrm,
            "read-only views require SeaORM"
        );
        for (model, fields) in [
            ("User", &["id", "email", "name"][..]),
            ("Pet", &["id", "owner_id"][..]),
            ("Membership", &["user_id", "group_id"][..]),
        ] {
            let spec = graph
                .models
                .iter()
                .find(|candidate| candidate.name == model)
                .with_context(|| format!("view extension requires model `{model}`"))?;
            for field in fields {
                ensure!(
                    spec.fields.iter().any(|candidate| candidate.name == *field),
                    "view extension requires field `{model}.{field}`"
                );
            }
        }

        Ok(vec![ModelExtensionFile {
            relative_path: PathBuf::from("src/model/user_activity_view.rs"),
            contents: render_user_activity_view(),
            ownership: ExtensionFileOwnership::Generated,
        }])
    }
}

fn render_user_activity_view() -> String {
    r#"// @generated by roze-ent-codegen. DO NOT EDIT.
#![allow(dead_code)]

use sea_orm::{
    sea_query::{Alias, Expr, Query},
    ConnectionTrait as _, FromQueryResult,
};
use serde::{Deserialize, Serialize};

use crate::svc::ServiceContext;

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, FromQueryResult)]
pub struct UserActivityView {
    pub user_id: i64,
    pub email: String,
    pub name: String,
    pub pet_count: i64,
    pub group_count: i64,
}

pub struct UserActivityViewRepository<'a> {
    ctx: &'a ServiceContext,
}

impl<'a> UserActivityViewRepository<'a> {
    pub fn new(ctx: &'a ServiceContext) -> Self {
        Self { ctx }
    }

    fn select() -> sea_orm::sea_query::SelectStatement {
        let view = Alias::new("user_activity_view");
        Query::select()
            .columns([
                Alias::new("user_id"),
                Alias::new("email"),
                Alias::new("name"),
                Alias::new("pet_count"),
                Alias::new("group_count"),
            ])
            .from(view)
            .to_owned()
    }

    pub async fn all(&self) -> anyhow::Result<Vec<UserActivityView>> {
        let db = self.ctx.read_db()?;
        let backend = db.get_database_backend();
        let statement = backend.build(&Self::select());
        Ok(UserActivityView::find_by_statement(statement)
            .all(db)
            .await?)
    }

    pub async fn find_by_user_id(&self, user_id: i64) -> anyhow::Result<Option<UserActivityView>> {
        let db = self.ctx.read_db()?;
        let backend = db.get_database_backend();
        let mut select = Self::select();
        select.and_where(Expr::col(Alias::new("user_id")).eq(user_id));
        let statement = backend.build(&select);
        Ok(UserActivityView::find_by_statement(statement)
            .one(db)
            .await?)
    }
}

#[cfg(test)]
mod tests {
    #[tokio::test]
    #[ignore = "requires ROZE_ENT_TEST_DATABASE_URL and applied view migrations"]
    async fn generated_view_is_query_only_and_has_real_sql_evidence() -> anyhow::Result<()> {
        let url = std::env::var("ROZE_ENT_TEST_DATABASE_URL")?;
        let config: crate::config::Config = serde_json::from_value(serde_json::json!({
            "name": "roze-ent-view-test",
            "profile": "test",
            "governance": {},
            "database": {
                "mode": "direct",
                "url": url,
                "max_connections": 2,
                "min_connections": 1
            }
        }))?;
        let ctx = crate::svc::ServiceContext::new(config).await?;
        let nonce = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)?
            .as_nanos();
        let user = ctx
            .model()
            .user()
            .create()
            .set_email(format!("view-{nonce}@example.com"))
            .set_name("View user".to_string())
            .save()
            .await?;
        ctx.model()
            .pet()
            .create()
            .set_owner(&user)
            .set_name("View pet".to_string())
            .set_species("other".to_string())
            .save()
            .await?;

        let row = super::UserActivityViewRepository::new(&ctx)
            .find_by_user_id(user.id)
            .await?
            .ok_or_else(|| anyhow::anyhow!("view row missing"))?;
        assert_eq!(row.user_id, user.id);
        assert_eq!(row.pet_count, 1);
        assert_eq!(row.group_count, 0);
        Ok(())
    }
}
"#
    .to_string()
}

fn main() -> anyhow::Result<()> {
    ensure!(
        MODEL_GENERATOR_EXTENSION_API_VERSION == 1,
        "unsupported rozectl model extension API version {}",
        MODEL_GENERATOR_EXTENSION_API_VERSION
    );
    let mut args = std::env::args_os().skip(1);
    let schema = PathBuf::from(
        args.next()
            .context("usage: roze-ent-codegen <schema> <out>")?,
    );
    let out = PathBuf::from(
        args.next()
            .context("usage: roze-ent-codegen <schema> <out>")?,
    );
    ensure!(
        args.next().is_none(),
        "usage: roze-ent-codegen <schema> <out>"
    );

    let source = fs::read_to_string(&schema)
        .with_context(|| format!("failed to read {}", schema.display()))?;
    let nonce = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)?
        .as_nanos();
    let staging =
        std::env::temp_dir().join(format!("roze-ent-codegen-{}-{nonce}", std::process::id()));
    let extension = RozeEntViewExtension;
    let result = (|| -> anyhow::Result<()> {
        generate_model_project_with_extensions(
            &source,
            &staging,
            GenerateOptions::new(GenerateMode::Create, DependencySource::Git),
            rozectl::generator::model::ModelFormat::Ent,
            ModelOrm::SeaOrm,
            &[&extension],
        )?;
        let relative = PathBuf::from("src/model/user_activity_view.rs");
        let generated = staging.join(&relative);
        let destination = out.join(&relative);
        let contents = fs::read(&generated)
            .with_context(|| format!("failed to read {}", generated.display()))?;
        fs::create_dir_all(destination.parent().context("view output has no parent")?)?;
        fs::write(&destination, contents)
            .with_context(|| format!("failed to write {}", destination.display()))?;
        Ok(())
    })();
    if staging.is_dir() {
        fs::remove_dir_all(&staging)
            .with_context(|| format!("failed to clean {}", staging.display()))?;
    }
    result
}
