#!/usr/bin/env bash
# Generated by rozectl.
# service: 'roze-ent'
# boundary: REST
# rest_routes: 16
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MANIFEST_PATH="${MANIFEST_PATH:-$PROJECT_ROOT/Cargo.toml}"
EVIDENCE_MANIFEST_PATH="$PROJECT_ROOT/ops/evidence-manifest.yaml"
CI_EVIDENCE_POLICY_PATH="$PROJECT_ROOT/ops/ci-evidence-policy.yaml"
VERIFY_REPORT_PATH="$PROJECT_ROOT/ops/production-verify-report.json"
DEPENDENCY_GOVERNANCE_PATH="$PROJECT_ROOT/ops/dependency-governance.yaml"
SKIP_TESTS="${SKIP_TESTS:-0}"
SKIP_EVIDENCE_INVENTORY="${SKIP_EVIDENCE_INVENTORY:-0}"
SERVICE_NAME='roze-ent'
BOUNDARY='REST'

run_step() {
  local name="$1"
  shift
  echo "==> $name"
  "$@"
}

check_dependency_transport_security() {
  local required_entry
  for required_entry in \
    'transport_security:' \
    'hostname_or_server_name_validation_required: true' \
    'client_certificate_and_private_key_must_be_paired: true' \
    'invalid_tls_update_keeps_last_valid_snapshot: true' \
    'plaintext_fallback_forbidden: true' \
    'transport_security_test_passed: true' \
  ; do
    if ! grep -Fq -- "$required_entry" "$DEPENDENCY_GOVERNANCE_PATH"; then
      echo "Dependency transport security contract is missing: $required_entry" >&2
      return 1
    fi
  done
}

json_escape() {
  local value="$1"
  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  value=${value//$'\n'/ }
  printf '%s' "$value"
}

required_ops_files=(
  'ops/production-evidence.md'
  'ops/governance-baseline.yaml'
  'ops/prometheus-rules.yaml'
  'ops/grafana-dashboard.json'
  'ops/slo.yaml'
  'ops/failure-injection-plan.yaml'
  'ops/release-rollout.yaml'
  'ops/incident-response.yaml'
  'ops/capacity-plan.yaml'
  'ops/security-readiness.yaml'
  'ops/production-gate.yaml'
  'ops/regeneration-policy.yaml'
  'ops/client-contract.yaml'
  'ops/config-governance.yaml'
  'ops/reliable-events.yaml'
  'ops/dependency-governance.yaml'
  'ops/data-consistency.yaml'
  'ops/observability-contract.yaml'
  'ops/runtime-hardening.yaml'
  'ops/error-contract.yaml'
  'ops/deployment-topology.yaml'
  'ops/service-communication.yaml'
  'ops/cache-governance.yaml'
  'ops/data-access-governance.yaml'
  'ops/interface-governance.yaml'
  'ops/production-verify.ps1'
  'ops/production-verify.sh'
  'ops/ci-evidence-policy.yaml'
  'ops/evidence-manifest.yaml'
  '.github/workflows/roze-production-verify.yml'
)

check_ops_inventory() {
  local relative_path
  local candidate
  for relative_path in "${required_ops_files[@]}"; do
    candidate="$PROJECT_ROOT/$relative_path"
    if [[ ! -e "$candidate" ]]; then
      echo "Missing generated ops asset: $relative_path" >&2
      return 1
    fi
  done
}

check_evidence_manifest_coverage() {
  local relative_path
  local manifest_entry
  for relative_path in "${required_ops_files[@]}"; do
    manifest_entry="path: $relative_path"
    if ! grep -Fq -- "$manifest_entry" "$EVIDENCE_MANIFEST_PATH"; then
      echo "Evidence manifest does not index generated asset entry: $manifest_entry" >&2
      return 1
    fi
  done
}

check_ci_evidence_policy_coverage() {
  local relative_path
  local policy_entry
  for relative_path in "${required_ops_files[@]}"; do
    policy_entry="    - $relative_path"
    if ! grep -Fq -- "$policy_entry" "$CI_EVIDENCE_POLICY_PATH"; then
      echo "CI evidence policy does not require generated asset path: $policy_entry" >&2
      return 1
    fi
  done
}

if [[ "$SKIP_EVIDENCE_INVENTORY" != "1" ]]; then
  run_step "generated ops asset inventory" check_ops_inventory
  run_step "evidence manifest coverage" check_evidence_manifest_coverage
  run_step "ci evidence policy coverage" check_ci_evidence_policy_coverage
fi

run_step "dependency transport security contract" check_dependency_transport_security

run_step "cargo fmt generated service" cargo fmt --manifest-path "$MANIFEST_PATH" -- --check
run_step "cargo check generated service" cargo check --manifest-path "$MANIFEST_PATH"
if [[ "$SKIP_TESTS" != "1" ]]; then
  run_step "cargo test generated service" cargo test --manifest-path "$MANIFEST_PATH"
fi

framework_smoke=(
  'GET /healthz'
  'GET /readyz'
  'GET /startupz'
  'GET /metrics'
  'GET /openapi.json'
  'POST /reports/exports'
  'POST /charts/query'
  'POST /users'
  'GET /users/:id'
  'GET /users'
  'DELETE /users/:id'
  'POST /pets'
  'GET /pets/:id'
  'GET /users/:id/pets'
  'DELETE /pets/:id'
  'POST /groups'
  'GET /groups/:id'
  'GET /groups'
  'POST /groups/:group_id/members/:user_id'
  'PATCH /groups/:group_id/members/:user_id'
  'DELETE /groups/:group_id/members/:user_id'
  'GET /groups/:id/users'
  'GET /users/:id/groups'
)
printf 'REST smoke endpoints required: %s\n' "${framework_smoke[*]}"
rustc_version="$(rustc --version)"
cargo_version="$(cargo --version)"
roze_revision="unknown"
if command -v git >/dev/null 2>&1 && git -C "$PROJECT_ROOT" rev-parse HEAD >/dev/null 2>&1; then
  roze_revision="$(git -C "$PROJECT_ROOT" rev-parse HEAD)"
fi
skip_tests_json=false
if [[ "$SKIP_TESTS" == "1" ]]; then skip_tests_json=true; fi
cat > "$VERIFY_REPORT_PATH" <<JSON
{
  "service": "$(json_escape "$SERVICE_NAME")",
  "boundary": "$(json_escape "${BOUNDARY,,}")",
  "generated_by": "rozectl",
  "verdict": "pass_ci_precondition",
  "broad_production": "requires_long_run_evidence",
  "skip_tests": $skip_tests_json,
  "timestamp_utc": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "os": "$(json_escape "$(uname -s)-$(uname -m)")",
  "rustc": "$(json_escape "$rustc_version")",
  "cargo": "$(json_escape "$cargo_version")",
  "roze_revision": "$(json_escape "$roze_revision")",
  "gates": ["generated_ops_asset_inventory", "evidence_manifest_coverage", "ci_evidence_policy_coverage", "dependency_transport_security_contract", "cargo_fmt_check", "cargo_check", "cargo_test_unless_skipped", "smoke_surface_declared", "production_verification_report_schema"],
  "required_followup_evidence": ["24h_or_72h_soak_report", "failure_injection_report", "dashboard_and_alert_evidence", "rollback_or_rollforward_evidence", "security_readiness_signoff", "capacity_and_resource_trend"]
}
JSON
check_verify_report_schema() {
  local required_entry
  if [[ ! -s "$VERIFY_REPORT_PATH" ]]; then
    echo 'Production verification report is missing or empty.' >&2
    return 1
  fi
  for required_entry in \
    '"generated_by": "rozectl"' \
    '"verdict": "pass_ci_precondition"' \
    '"broad_production": "requires_long_run_evidence"' \
    '"dependency_transport_security_contract"' \
    '"production_verification_report_schema"' \
    '"24h_or_72h_soak_report"' \
  ; do
    if ! grep -Fq -- "$required_entry" "$VERIFY_REPORT_PATH"; then
      echo "Production verification report is missing required contract entry: $required_entry" >&2
      return 1
    fi
  done
}
run_step "production verification report schema" check_verify_report_schema
printf 'Production verification report: %s\n' "$VERIFY_REPORT_PATH"
printf 'Production verification passed for %s (%s). Attach long-run soak, failure-injection, dashboard, alert, and rollback evidence before broad rollout.\n' "$SERVICE_NAME" "$BOUNDARY"
