# Generated by rozectl.
# service: roze-ent
# boundary: REST
# rest_routes: 8
param(
    [switch]$SkipTests,
    [switch]$SkipEvidenceInventory,
    [string]$ManifestPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'Cargo.toml')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$ServiceName = 'roze-ent'
$Boundary = 'REST'

function Invoke-Step {
    param(
        [Parameter(Mandatory = $true)][string]$Name,
        [Parameter(Mandatory = $true)][scriptblock]$Command
    )
    Write-Host "==> $Name"
    $global:LASTEXITCODE = 0
    & $Command
    if ($LASTEXITCODE -ne 0) {
        throw "$Name failed with exit code $LASTEXITCODE"
    }
}

$requiredOpsFiles = @(
    'ops/production-evidence.md'
    'ops/governance-baseline.yaml'
    'ops/prometheus-rules.yaml'
    'ops/grafana-dashboard.json'
    'ops/slo.yaml'
    'ops/failure-injection-plan.yaml'
    'ops/release-rollout.yaml'
    'ops/incident-response.yaml'
    'ops/capacity-plan.yaml'
    'ops/security-readiness.yaml'
    'ops/production-gate.yaml'
    'ops/regeneration-policy.yaml'
    'ops/client-contract.yaml'
    'ops/config-governance.yaml'
    'ops/reliable-events.yaml'
    'ops/dependency-governance.yaml'
    'ops/data-consistency.yaml'
    'ops/observability-contract.yaml'
    'ops/runtime-hardening.yaml'
    'ops/error-contract.yaml'
    'ops/deployment-topology.yaml'
    'ops/service-communication.yaml'
    'ops/cache-governance.yaml'
    'ops/data-access-governance.yaml'
    'ops/interface-governance.yaml'
    'ops/production-verify.ps1'
    'ops/production-verify.sh'
    'ops/ci-evidence-policy.yaml'
    'ops/evidence-manifest.yaml'
    '.github/workflows/roze-production-verify.yml'
)

$EvidenceManifestPath = Join-Path $ProjectRoot 'ops/evidence-manifest.yaml'
$CiEvidencePolicyPath = Join-Path $ProjectRoot 'ops/ci-evidence-policy.yaml'
$VerifyReportPath = Join-Path $ProjectRoot 'ops/production-verify-report.json'
$DependencyGovernancePath = Join-Path $ProjectRoot 'ops/dependency-governance.yaml'

if (-not $SkipEvidenceInventory) {
    Invoke-Step 'generated ops asset inventory' {
        foreach ($relativePath in $requiredOpsFiles) {
            $candidate = Join-Path $ProjectRoot $relativePath
            if (-not (Test-Path -LiteralPath $candidate)) {
                throw "Missing generated ops asset: $relativePath"
            }
        }
    }
    Invoke-Step 'evidence manifest coverage' {
        $manifest = Get-Content -LiteralPath $EvidenceManifestPath -Raw
        foreach ($relativePath in $requiredOpsFiles) {
            $manifestEntry = "path: $relativePath"
            if (-not $manifest.Contains($manifestEntry)) {
                throw "Evidence manifest does not index generated asset entry: $manifestEntry"
            }
        }
    }
    Invoke-Step 'ci evidence policy coverage' {
        $policy = Get-Content -LiteralPath $CiEvidencePolicyPath -Raw
        foreach ($relativePath in $requiredOpsFiles) {
            $policyEntry = "    - $relativePath"
            if (-not $policy.Contains($policyEntry)) {
                throw "CI evidence policy does not require generated asset path: $policyEntry"
            }
        }
    }
}

Invoke-Step 'dependency transport security contract' {
    $dependencyGovernance = Get-Content -LiteralPath $DependencyGovernancePath -Raw
    foreach ($requiredEntry in @(
        'transport_security:'
        'hostname_or_server_name_validation_required: true'
        'client_certificate_and_private_key_must_be_paired: true'
        'invalid_tls_update_keeps_last_valid_snapshot: true'
        'plaintext_fallback_forbidden: true'
        'transport_security_test_passed: true'
    )) {
        if (-not $dependencyGovernance.Contains($requiredEntry)) {
            throw "Dependency transport security contract is missing: $requiredEntry"
        }
    }
}

Invoke-Step 'cargo fmt generated service' { cargo fmt --manifest-path $ManifestPath -- --check }
Invoke-Step 'cargo check generated service' { cargo check --manifest-path $ManifestPath }
if (-not $SkipTests) {
    Invoke-Step 'cargo test generated service' { cargo test --manifest-path $ManifestPath }
}

$frameworkSmoke = @(
    'GET /healthz'
    'GET /readyz'
    'GET /startupz'
    'GET /metrics'
    'GET /openapi.json'
    'POST /reports/exports'
    'POST /charts/query'
    'POST /users'
    'GET /users/:id'
    'GET /users'
    'DELETE /users/:id'
    'POST /pets'
    'GET /pets/:id'
    'GET /users/:id/pets'
    'DELETE /pets/:id'
)
Write-Host ('REST smoke endpoints required: ' + ($frameworkSmoke -join ', '))
$rustcVersion = (& rustc --version) -join ''
$cargoVersion = (& cargo --version) -join ''
$rozeRevision = 'unknown'
if (Get-Command git -ErrorAction SilentlyContinue) {
    $gitRevision = & git -C $ProjectRoot rev-parse HEAD 2>$null
    if ($LASTEXITCODE -eq 0) { $rozeRevision = ($gitRevision -join '') }
}
$verifyReport = [ordered]@{
    service = $ServiceName
    boundary = $Boundary.ToLowerInvariant()
    generated_by = 'rozectl'
    verdict = 'pass_ci_precondition'
    broad_production = 'requires_long_run_evidence'
    skip_tests = [bool]$SkipTests
    timestamp_utc = (Get-Date).ToUniversalTime().ToString('o')
    os = [System.Runtime.InteropServices.RuntimeInformation]::OSDescription
    rustc = $rustcVersion
    cargo = $cargoVersion
    roze_revision = $rozeRevision
    gates = @(
        'generated_ops_asset_inventory'
        'evidence_manifest_coverage'
        'ci_evidence_policy_coverage'
        'dependency_transport_security_contract'
        'cargo_fmt_check'
        'cargo_check'
        'cargo_test_unless_skipped'
        'smoke_surface_declared'
        'production_verification_report_schema'
    )
    required_followup_evidence = @(
        '24h_or_72h_soak_report'
        'failure_injection_report'
        'dashboard_and_alert_evidence'
        'rollback_or_rollforward_evidence'
        'security_readiness_signoff'
        'capacity_and_resource_trend'
    )
}
$verifyReport | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath $VerifyReportPath -Encoding UTF8
Invoke-Step 'production verification report schema' {
    $report = Get-Content -LiteralPath $VerifyReportPath -Raw | ConvertFrom-Json
    if ($report.service -ne $ServiceName) { throw 'Verification report service does not match generated service.' }
    if ($report.boundary -ne $Boundary.ToLowerInvariant()) { throw 'Verification report boundary does not match generated boundary.' }
    if ($report.generated_by -ne 'rozectl') { throw 'Verification report generator identity is invalid.' }
    if ($report.verdict -ne 'pass_ci_precondition') { throw 'Verification report verdict is invalid.' }
    if ($report.broad_production -ne 'requires_long_run_evidence') { throw 'Verification report production scope is invalid.' }
    if (-not ($report.gates -contains 'production_verification_report_schema')) { throw 'Verification report schema gate is missing.' }
    if (-not ($report.gates -contains 'dependency_transport_security_contract')) { throw 'Verification report dependency transport security gate is missing.' }
    if (-not ($report.required_followup_evidence -contains '24h_or_72h_soak_report')) { throw 'Verification report long-run evidence requirement is missing.' }
}
Write-Host "Production verification report: $VerifyReportPath"
Write-Host "Production verification passed for $ServiceName ($Boundary). Attach long-run soak, failure-injection, dashboard, alert, and rollback evidence before broad rollout."
